#!/bin/sh
set -eu

# Generate the router preset file and the tier directories from the registry.
#
# llama-server in router mode reads an INI whose sections name models and whose
# keys are LLAMA_ARG_* option names. It builds a base preset from its own argv,
# strips the SSL, API key, and models-* keys from it, and cascades the rest onto
# every child it spawns. The guarded argv that qwen-capacity-policy.sh already
# builds therefore reaches each child unchanged, and this file carries only what
# differs per checkpoint: the weights, the projector, the admitted depth, the
# cache triple, and the labels the picker shows.
#
# qwen-capacity-policy.sh refuses ambient LLAMA_ARG_* precisely so the caller's
# environment cannot override the computed argv. An INI the policy generates is
# that computation's output rather than ambient input, so the refusal stands.
#
# The tier field decides both the directory a checkpoint is linked into and the
# tag the picker groups it by. A row tiered archive is linked nowhere and named
# in no section, which is what removes it from the picker while leaving the
# weights on disk and the fetch script that verifies them in the tree.
#
# Directories are linked rather than moved. A checkpoint's projector must sit in
# the checkpoint's own directory for remote/select-projector.sh to pair it, and
# linking the directory preserves that pairing while a file move would break a
# reader holding the model open.

if [ "$#" -gt 1 ]; then
    printf 'usage: %s [OUTPUT_INI]\n' "$0" >&2
    printf 'model root comes from QWEN_MODEL_ROOT, default $HOME/models\n' >&2
    exit 2
fi

script_directory=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
registry=${QWEN_MODEL_REGISTRY:-$script_directory/models.tsv}
model_root=${QWEN_MODEL_ROOT:-"${HOME:?}/models"}
output_ini=${1:-"${HOME:?}/qwen-webui-state/router-presets.ini"}

if [ ! -r "$registry" ]; then
    printf 'model registry is unreadable: %s\n' "$registry" >&2
    exit 1
fi

mkdir -p "$(dirname -- "$output_ini")"
production_directory=$model_root/production
candidate_directory=$model_root/candidates
mkdir -p "$production_directory" "$candidate_directory"

# A stale link outlives the row that created it, so the tier directories are
# emptied of links before they are rebuilt. Only symbolic links are removed,
# which leaves a real directory placed there by hand untouched.
for tier_directory in "$production_directory" "$candidate_directory"; do
    for existing in "$tier_directory"/*; do
        if [ -L "$existing" ]; then
            rm -f "$existing"
        fi
    done
done

emitted=0
skipped_archive=0
skipped_absent=0

{
    printf '# Generated by remote/build-router-presets.sh from the model registry.\n'
    printf '# Edit remote/models.tsv and regenerate; edits here are overwritten.\n'
    printf '\n'
} >"$output_ini"

while IFS='	' read -r id role model_file fetch_script context_default \
    context_ceiling context_target cache_type_k cache_type_v flash_attention \
    projector decode_tok_s prefill_tok_s quality tier; do
    case $id in
        '#'* | '') continue ;;
    esac
    [ -n "${tier:-}" ] || continue

    if [ "$tier" = archive ]; then
        skipped_archive=$((skipped_archive + 1))
        continue
    fi

    model_path=$model_root/$model_file
    if [ ! -f "$model_path" ]; then
        printf 'preset_skipped id=%s reason=weights_absent path=%s\n' \
            "$id" "$model_path" >&2
        skipped_absent=$((skipped_absent + 1))
        continue
    fi

    case $tier in
        production) tier_directory=$production_directory ;;
        *) tier_directory=$candidate_directory ;;
    esac
    model_directory=$(dirname -- "$model_path")
    ln -sfn "$model_directory" "$tier_directory/$(basename -- "$model_directory")"

    {
        printf '[%s]\n' "$id"
        printf 'LLAMA_ARG_MODEL = %s\n' "$model_path"
        printf 'LLAMA_ARG_ALIAS = %s\n' "$id"
        printf 'LLAMA_ARG_TAGS = %s,%s\n' "$tier" "$role"
        printf 'LLAMA_ARG_CTX_SIZE = %s\n' "$context_default"
        printf 'LLAMA_ARG_CACHE_TYPE_K = %s\n' "$cache_type_k"
        printf 'LLAMA_ARG_CACHE_TYPE_V = %s\n' "$cache_type_v"
        printf 'LLAMA_ARG_FLASH_ATTN = %s\n' "$flash_attention"
    } >>"$output_ini"

    if [ "$projector" = required ]; then
        projector_path=$("$script_directory/select-projector.sh" "$model_path" \
            2>/dev/null) || projector_path=''
        if [ -n "$projector_path" ]; then
            printf 'LLAMA_ARG_MMPROJ = %s\n' "$projector_path" >>"$output_ini"
        else
            printf 'preset_warning id=%s reason=projector_unresolved\n' "$id" >&2
        fi
    fi
    printf '\n' >>"$output_ini"
    emitted=$((emitted + 1))
done <"$registry"

printf 'router_presets=written path=%s models=%s archived=%s absent=%s\n' \
    "$output_ini" "$emitted" "$skipped_archive" "$skipped_absent"
printf 'tier_directories production=%s candidates=%s\n' \
    "$production_directory" "$candidate_directory"
