#!/bin/sh
set -eu

# Generate the web-enabled router preset file from remote/web-profiles.tsv,
# joined against remote/models.tsv for the tuple each profile's model_id
# serves at.
#
# Router mode overlays every per-model preset key with its own CLI argument
# (server-models.cpp ends its preset assembly with preset.merge(base_preset),
# and common_preset::merge overwrites), so an absent key falls through to a
# llama.cpp default a section never chose. Every emitted section therefore
# carries all six geometry keys -- ctx-size, batch-size, ubatch-size,
# cache-type-k, cache-type-v, flash-attn -- read from the model_id's own
# registry row rather than left to inherit one.
#
# mcp-servers-config names the MCP server configuration a web-enabled section
# runs against. No default path is safe to assume for a tool-bearing section,
# so QWEN_WEB_MCP_CONFIG is required and its absence refuses the run rather
# than emitting a section with tool access misconfigured by omission.
#
# The generator refuses a profile whose model_id is not tiered production or
# candidate, and refuses a profile whose context exceeds the registry row's
# context_ceiling: a context above the depth the policy admits requests an
# allocation the row was never measured to support. It also refuses a profile
# whose context exceeds the row's validated_filled_depth when that field is
# not `-`, because a context that loads is a different claim from a context
# that fills and decodes; QWEN_WEB_ALLOW_UNVALIDATED_DEPTH=1 downgrades that
# refusal to a warning naming the gap, for a caller who accepts an unvalidated
# depth deliberately.

if [ "$#" -ne 1 ]; then
    printf 'usage: %s OUTPUT_INI\n' "$0" >&2
    printf 'model registry comes from QWEN_MODEL_REGISTRY, default remote/models.tsv\n' >&2
    printf 'web profile ledger comes from QWEN_WEB_PROFILES, default remote/web-profiles.tsv\n' >&2
    printf 'model root comes from QWEN_MODEL_ROOT, default $HOME/models\n' >&2
    printf 'mcp config path is required in QWEN_WEB_MCP_CONFIG\n' >&2
    printf 'QWEN_WEB_ALLOW_UNVALIDATED_DEPTH=1 downgrades an unvalidated-depth refusal to a warning\n' >&2
    exit 2
fi

script_directory=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
registry=${QWEN_MODEL_REGISTRY:-$script_directory/models.tsv}
web_profiles=${QWEN_WEB_PROFILES:-$script_directory/web-profiles.tsv}
model_root=${QWEN_MODEL_ROOT:-"${HOME:?}/models"}
output_ini=$1
allow_unvalidated_depth=${QWEN_WEB_ALLOW_UNVALIDATED_DEPTH:-0}
case $allow_unvalidated_depth in
    0 | 1) ;;
    *)
        printf 'QWEN_WEB_ALLOW_UNVALIDATED_DEPTH must be 0 or 1: %s\n' \
            "$allow_unvalidated_depth" >&2
        exit 2
        ;;
esac

mcp_servers_config=${QWEN_WEB_MCP_CONFIG:-}
if [ -z "$mcp_servers_config" ]; then
    printf 'QWEN_WEB_MCP_CONFIG must name the MCP servers config path\n' >&2
    exit 1
fi

if [ ! -r "$registry" ]; then
    printf 'model registry is unreadable: %s\n' "$registry" >&2
    exit 1
fi
if [ ! -r "$web_profiles" ]; then
    printf 'web profile ledger is unreadable: %s\n' "$web_profiles" >&2
    exit 1
fi

mkdir -p "$(dirname -- "$output_ini")"

{
    printf '# Generated by remote/build-web-presets.sh from remote/web-profiles.tsv.\n'
    printf '# Edit remote/web-profiles.tsv and regenerate; edits here are overwritten.\n'
    printf '\n'
} >"$output_ini"

emitted=0

registry_field() {
    registry_field_row=$1
    registry_field_name=$2
    printf '%s\n' "$registry_field_row" | sed -n "s/^$registry_field_name=//p"
}

while IFS='	' read -r profile_id model_id web_mode context \
    _ledger_validated_filled_depth _max_results _max_fetches _max_chars_per_fetch \
    _multi_source _vision_allowed _tool_selection _execution_policy; do
    case $profile_id in
        '#'* | '') continue ;;
    esac

    if ! registry_row=$("$script_directory/model-registry.sh" id "$model_id"); then
        printf 'profile %s names unknown model_id %s\n' "$profile_id" "$model_id" >&2
        exit 1
    fi

    model_file=$(registry_field "$registry_row" model_file)
    context_ceiling=$(registry_field "$registry_row" context_ceiling)
    cache_type_k=$(registry_field "$registry_row" cache_type_k)
    cache_type_v=$(registry_field "$registry_row" cache_type_v)
    flash_attention=$(registry_field "$registry_row" flash_attention)
    tier=$(registry_field "$registry_row" tier)
    batch=$(registry_field "$registry_row" batch)
    ubatch=$(registry_field "$registry_row" ubatch)
    registry_validated_filled_depth=$(registry_field "$registry_row" validated_filled_depth)

    case $tier in
        production | candidate) ;;
        *)
            printf 'profile %s names model %s at tier %s, which is not production or candidate\n' \
                "$profile_id" "$model_id" "$tier" >&2
            exit 1
            ;;
    esac

    if [ "$context" -gt "$context_ceiling" ] 2>/dev/null; then
        printf 'profile %s requests context %s above %s ceiling %s\n' \
            "$profile_id" "$context" "$model_id" "$context_ceiling" >&2
        exit 1
    fi

    if [ "$registry_validated_filled_depth" != '-' ] &&
        [ "$context" -gt "$registry_validated_filled_depth" ] 2>/dev/null; then
        if [ "$allow_unvalidated_depth" = 1 ]; then
            printf 'web_preset_warning profile=%s context=%s exceeds validated_filled_depth=%s for model=%s\n' \
                "$profile_id" "$context" "$registry_validated_filled_depth" "$model_id" >&2
        else
            printf 'profile %s requests context %s above %s validated_filled_depth %s\n' \
                "$profile_id" "$context" "$model_id" "$registry_validated_filled_depth" >&2
            exit 1
        fi
    fi

    model_path=$model_root/$model_file

    {
        printf '[%s]\n' "$profile_id"
        printf 'model = %s\n' "$model_path"
        printf 'ctx-size = %s\n' "$context"
        printf 'batch-size = %s\n' "$batch"
        printf 'ubatch-size = %s\n' "$ubatch"
        printf 'cache-type-k = %s\n' "$cache_type_k"
        printf 'cache-type-v = %s\n' "$cache_type_v"
        printf 'flash-attn = %s\n' "$flash_attention"
        printf 'mcp-servers-config = %s\n' "$mcp_servers_config"
        printf 'tags = web-research,%s\n' "$web_mode"
        printf '\n'
    } >>"$output_ini"

    emitted=$((emitted + 1))
done <"$web_profiles"

printf 'web_presets=written path=%s profiles=%s\n' "$output_ini" "$emitted"
