#!/bin/sh
set -eu

# Generate the web-enabled router preset file from remote/web-profiles.tsv,
# joined against remote/models.tsv for the tuple each profile's model_id
# serves at.
#
# Router mode overlays every per-model preset key with its own CLI argument
# (server-models.cpp ends its preset assembly with preset.merge(base_preset),
# and common_preset::merge overwrites), so an absent key falls through to a
# llama.cpp default a section never chose. Every emitted section therefore
# carries all six geometry keys -- ctx-size, batch-size, ubatch-size,
# cache-type-k, cache-type-v, flash-attn -- read from the model_id's own
# registry row rather than left to inherit one.
#
# mcp-servers-config names the MCP server configuration a web-enabled section
# runs against. No default path is safe to assume for a tool-bearing section,
# so QWEN_WEB_MCP_CONFIG is required and its absence refuses the run rather
# than emitting a section with tool access misconfigured by omission.
#
# The generator refuses a profile whose model_id is not tiered production or
# candidate, and refuses a profile whose context exceeds the registry row's
# context_ceiling: a context above the depth the policy admits requests an
# allocation the row was never measured to support.
#
# Unknown is not permission. The default rule is context <= numeric
# validated_filled_depth, so a `-` field, which states that no depth has been
# filled and decoded on that row, refuses the profile exactly as an
# over-numeric context does. QWEN_WEB_ALLOW_UNVALIDATED_DEPTH=1 admits a
# profile that fails that rule, and only that profile: it prints a stderr line
# naming the unknown state or the numeric gap, tags the section
# `experimental` in `tags`, and writes the file-head marker
# `# qwen-web-presets: unvalidated-depth-override`, mirroring how
# build-router-presets.sh records QWEN_ROUTER_INCLUDE_QUARANTINE in its own
# preamble so a later reader can force the listener to loopback the same way
# qwen-capacity-policy.sh does for an exposed quarantine section. The override
# never reaches a production-tier profile: `production` claims a tuple
# measured safe and useful, and admitting one at an unvalidated depth would
# misstate that claim, so a production row still refuses regardless of the
# override.

if [ "$#" -ne 1 ]; then
    printf 'usage: %s OUTPUT_INI\n' "$0" >&2
    printf 'model registry comes from QWEN_MODEL_REGISTRY, default remote/models.tsv\n' >&2
    printf 'web profile ledger comes from QWEN_WEB_PROFILES, default remote/web-profiles.tsv\n' >&2
    printf 'model root comes from QWEN_MODEL_ROOT, default $HOME/models\n' >&2
    printf 'mcp config path is required in QWEN_WEB_MCP_CONFIG\n' >&2
    printf 'QWEN_WEB_ALLOW_UNVALIDATED_DEPTH=1 admits an unknown or over-depth candidate-tier profile as experimental\n' >&2
    exit 2
fi

script_directory=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
registry=${QWEN_MODEL_REGISTRY:-$script_directory/models.tsv}
web_profiles=${QWEN_WEB_PROFILES:-$script_directory/web-profiles.tsv}
model_root=${QWEN_MODEL_ROOT:-"${HOME:?}/models"}
output_ini=$1
allow_unvalidated_depth=${QWEN_WEB_ALLOW_UNVALIDATED_DEPTH:-0}
case $allow_unvalidated_depth in
    0 | 1) ;;
    *)
        printf 'QWEN_WEB_ALLOW_UNVALIDATED_DEPTH must be 0 or 1: %s\n' \
            "$allow_unvalidated_depth" >&2
        exit 2
        ;;
esac

mcp_servers_config=${QWEN_WEB_MCP_CONFIG:-}
if [ -z "$mcp_servers_config" ]; then
    printf 'QWEN_WEB_MCP_CONFIG must name the MCP servers config path\n' >&2
    exit 1
fi

if [ ! -r "$registry" ]; then
    printf 'model registry is unreadable: %s\n' "$registry" >&2
    exit 1
fi
if [ ! -r "$web_profiles" ]; then
    printf 'web profile ledger is unreadable: %s\n' "$web_profiles" >&2
    exit 1
fi

mkdir -p "$(dirname -- "$output_ini")"

{
    printf '# Generated by remote/build-web-presets.sh from remote/web-profiles.tsv.\n'
    printf '# Edit remote/web-profiles.tsv and regenerate; edits here are overwritten.\n'
    if [ "$allow_unvalidated_depth" = 1 ]; then
        printf '# qwen-web-presets: unvalidated-depth-override\n'
    fi
    printf '\n'
} >"$output_ini"

emitted=0

registry_field() {
    registry_field_row=$1
    registry_field_name=$2
    printf '%s\n' "$registry_field_row" | sed -n "s/^$registry_field_name=//p"
}

while IFS='	' read -r profile_id model_id web_mode context \
    _ledger_validated_filled_depth _max_results _max_fetches _max_chars_per_fetch \
    _multi_source _vision_allowed _tool_selection _execution_policy; do
    case $profile_id in
        '#'* | '') continue ;;
    esac

    if ! registry_row=$("$script_directory/model-registry.sh" id "$model_id"); then
        printf 'profile %s names unknown model_id %s\n' "$profile_id" "$model_id" >&2
        exit 1
    fi

    model_file=$(registry_field "$registry_row" model_file)
    context_ceiling=$(registry_field "$registry_row" context_ceiling)
    cache_type_k=$(registry_field "$registry_row" cache_type_k)
    cache_type_v=$(registry_field "$registry_row" cache_type_v)
    flash_attention=$(registry_field "$registry_row" flash_attention)
    tier=$(registry_field "$registry_row" tier)
    batch=$(registry_field "$registry_row" batch)
    ubatch=$(registry_field "$registry_row" ubatch)
    registry_validated_filled_depth=$(registry_field "$registry_row" validated_filled_depth)

    case $tier in
        production | candidate) ;;
        *)
            printf 'profile %s names model %s at tier %s, which is not production or candidate\n' \
                "$profile_id" "$model_id" "$tier" >&2
            exit 1
            ;;
    esac

    if [ "$context" -gt "$context_ceiling" ] 2>/dev/null; then
        printf 'profile %s requests context %s above %s ceiling %s\n' \
            "$profile_id" "$context" "$model_id" "$context_ceiling" >&2
        exit 1
    fi

    # Unknown is not permission: a `-` field and a numeric field the context
    # exceeds both fail the default rule, and only the override's own
    # production-tier exclusion tells them apart below.
    depth_state=validated
    if [ "$registry_validated_filled_depth" = '-' ]; then
        depth_state=unknown
    elif [ "$context" -gt "$registry_validated_filled_depth" ] 2>/dev/null; then
        depth_state=exceeded
    fi

    tags_suffix=
    if [ "$depth_state" != validated ]; then
        if [ "$allow_unvalidated_depth" != 1 ]; then
            if [ "$depth_state" = unknown ]; then
                printf 'profile %s requests context %s against %s validated_filled_depth unknown (-)\n' \
                    "$profile_id" "$context" "$model_id" >&2
            else
                printf 'profile %s requests context %s above %s validated_filled_depth %s\n' \
                    "$profile_id" "$context" "$model_id" "$registry_validated_filled_depth" >&2
            fi
            exit 1
        fi
        if [ "$tier" = production ]; then
            printf 'profile %s names production-tier model %s at an unvalidated depth; production refuses the override\n' \
                "$profile_id" "$model_id" >&2
            exit 1
        fi
        if [ "$depth_state" = unknown ]; then
            printf 'web_preset_warning profile=%s validated_filled_depth=unknown model=%s\n' \
                "$profile_id" "$model_id" >&2
        else
            depth_gap=$((context - registry_validated_filled_depth))
            printf 'web_preset_warning profile=%s validated_filled_depth_gap=%s model=%s\n' \
                "$profile_id" "$depth_gap" "$model_id" >&2
        fi
        tags_suffix=,experimental
    fi

    model_path=$model_root/$model_file

    {
        printf '[%s]\n' "$profile_id"
        printf 'model = %s\n' "$model_path"
        printf 'ctx-size = %s\n' "$context"
        printf 'batch-size = %s\n' "$batch"
        printf 'ubatch-size = %s\n' "$ubatch"
        printf 'cache-type-k = %s\n' "$cache_type_k"
        printf 'cache-type-v = %s\n' "$cache_type_v"
        printf 'flash-attn = %s\n' "$flash_attention"
        printf 'mcp-servers-config = %s\n' "$mcp_servers_config"
        printf 'tags = web-research,%s%s\n' "$web_mode" "$tags_suffix"
        printf '\n'
    } >>"$output_ini"

    emitted=$((emitted + 1))
done <"$web_profiles"

printf 'web_presets=written path=%s profiles=%s\n' "$output_ini" "$emitted"
