"""The runtime root, resolved the way remote/qwen-home.sh resolves it.

QWEN_HOME names the one directory every generated byte lives under and
defaults to `.runtime` beside the `remote/` directory this module sits in, so
a python child reads the same root as the shell script that started it
without the value having to cross an environment boundary.
"""

from __future__ import annotations

import os
from pathlib import Path

RUNTIME_SCHEMA_VERSION = 1

_DECLARED = {
    "bin": "bin",
    "opt": "opt",
    "models": "models",
    "deployments": "deployments",
    "state": "state",
    "cache": "cache",
    "tmp": "tmp",
    "results": "results",
    "browser_python": "opt/browser-venv/bin/python",
    "llama_source": "opt/llama.cpp",
    "image_source": "opt/stable-diffusion.cpp",
    "image_runtime": "opt/stable-diffusion.cpp/build-raven2/bin/sd-cli",
    "gguf_py": "opt/llama.cpp/gguf-py",
    "ryzenadj": "bin/ryzenadj",
    "searxng_root": "opt/searxng",
    "searxng_source": "opt/searxng/src",
    "searxng_python": "opt/searxng/venv/bin/python",
    "web_token_key": "state/web-token.key",
    "image_parameters": "state/image-parameters.json",
    "manifest": "manifest.tsv",
    "marker": ".qwen-runtime-root",
}


def tree_root() -> Path:
    """The tree that holds remote/, which is the tree whose root is read."""
    return Path(__file__).resolve().parent.parent


def home() -> Path:
    value = os.environ.get("QWEN_HOME")
    if value:
        root = Path(value)
        if not root.is_absolute():
            raise ValueError(f"QWEN_HOME must be an absolute path: {value}")
        return root
    return tree_root() / ".runtime"


def path(name: str) -> Path:
    try:
        relative = _DECLARED[name]
    except KeyError as error:
        raise KeyError(f"unknown runtime root name: {name}") from error
    return home() / relative


def binding_state() -> str:
    """How the root's marker binds it to a checkout.

    `unmarked` is a root `make bootstrap` has yet to lay out, `bound` is a
    marker whose tree_root resolves to the tree this module sits in, and
    `foreign:TREE` is a root laid out beside another checkout. A python child
    reads the same three states remote/qwen-home.sh reports, so a caller that
    resolves the root itself refuses what the shell entry points refuse.
    """
    try:
        text = path("marker").read_text(encoding="utf-8")
    except OSError:
        return "unmarked"
    named = ""
    for line in text.splitlines():
        if line.startswith("tree_root="):
            named = line[len("tree_root=") :]
            break
    if not named:
        return "foreign:unnamed"
    resolved = Path(named)
    if resolved.is_dir():
        resolved = resolved.resolve()
    if resolved == tree_root():
        return "bound"
    return f"foreign:{resolved}"


def require_binding() -> None:
    """Raise where the root's marker names another checkout."""
    state = binding_state()
    if state in ("bound", "unmarked"):
        return
    raise RuntimeError(
        f"{home()} is bound to {state[len('foreign:') :]} and this tree is "
        f"{tree_root()}; run make bootstrap in the checkout the marker names"
    )
