#!/bin/sh
# The runtime root: one declared directory every generated byte of the
# appliance lives under.
#
# A checkout of this repository is the complete declaration of the appliance,
# and `make bootstrap` expands that declaration into one ignored tree beside
# it. QWEN_HOME names that tree and defaults to `.runtime` directly under the
# tree that holds `remote/`, so the copy that runs is the copy whose runtime
# root is read: a synced runtime tree and a git checkout each resolve their
# own. An operator moves the root to another disk by exporting QWEN_HOME, and
# every path below follows it. The default is repo-local rather than a
# home-directory sibling because a second external directory reopens the
# question this library closes: which directory is authoritative.
#
# Sourced from a script that has set script_directory, the library sets one
# lowercase variable per declared location and exports QWEN_HOME alone, so a
# caller reads `${QWEN_MODEL_ROOT:-$qwen_home_models}` and an explicit
# override keeps its meaning while an unset variable stays unset. Run as a
# command, `print NAME...` answers the Makefile and the manifest with the same
# values.
#
# usage: . "$script_directory/qwen-home.sh"
#        qwen-home.sh print NAME [NAME...]   one value per line
#        qwen-home.sh paths                  every declared name and value

qwen_home_names='qwen_tree_root qwen_home qwen_home_marker qwen_home_manifest
qwen_home_bin qwen_home_opt qwen_home_models qwen_home_deployments
qwen_home_state qwen_home_cache qwen_home_tmp qwen_home_results
qwen_home_build_cache qwen_home_gate_cache qwen_home_gate_venv
qwen_home_llama_source qwen_home_llama_server qwen_home_llama_bench
qwen_home_llama_cli qwen_home_llama_quantize qwen_home_gguf_py
qwen_home_llama_upstream qwen_home_llama_trace qwen_home_llama_census_bench qwen_home_radv_root
qwen_home_image_source qwen_home_image_runtime
qwen_home_ryzenadj_source qwen_home_ryzenadj
qwen_home_shaderc_root qwen_home_searxng_root qwen_home_searxng_source
qwen_home_searxng_python qwen_home_yacy qwen_home_rocm
qwen_home_web_token_key qwen_home_image_parameters'
qwen_home_names=$(printf '%s' "$qwen_home_names" | tr '\n' ' ')

# shellcheck disable=SC2034  # each name is read by the script that sources this library
qwen_home_resolve() {
    qwen_home_library_directory=$1
    qwen_tree_root=$(CDPATH='' cd -- "$qwen_home_library_directory/.." && pwd -P)
    qwen_home=${QWEN_HOME:-"$qwen_tree_root/.runtime"}
    case $qwen_home in
        /*) ;;
        *)
            printf 'QWEN_HOME must be an absolute path: %s\n' "$qwen_home" >&2
            return 2
            ;;
    esac
    QWEN_HOME=$qwen_home
    export QWEN_HOME
    qwen_home_marker=$qwen_home/.qwen-runtime-root
    qwen_home_manifest=$qwen_home/manifest.tsv
    qwen_home_bin=$qwen_home/bin
    qwen_home_opt=$qwen_home/opt
    qwen_home_models=$qwen_home/models
    qwen_home_deployments=$qwen_home/deployments
    qwen_home_state=$qwen_home/state
    qwen_home_cache=$qwen_home/cache
    qwen_home_tmp=$qwen_home/tmp
    qwen_home_results=$qwen_home/results
    qwen_home_build_cache=$qwen_home_cache/build
    qwen_home_gate_cache=$qwen_home_cache/gate
    qwen_home_gate_venv=$qwen_home_opt/gate-venv
    qwen_home_llama_source=$qwen_home_opt/llama.cpp
    qwen_home_llama_server=$qwen_home_llama_source/build-appliance-current/bin/llama-server
    qwen_home_llama_bench=$qwen_home_llama_source/build-qwen-vulkan/bin/llama-bench
    qwen_home_llama_cli=$qwen_home_llama_source/build-qwen-vulkan/bin/llama-cli
    qwen_home_llama_quantize=$qwen_home_llama_source/build-qwen-vulkan/bin/llama-quantize
    qwen_home_gguf_py=$qwen_home_llama_source/gguf-py
    qwen_home_llama_upstream=$qwen_home_opt/llama.cpp-upstream
    qwen_home_llama_trace=$qwen_home_opt/llama.cpp-trace
    qwen_home_llama_census_bench=$qwen_home_opt/llama.cpp-census/build-raven2-vulkan-census/bin/llama-bench
    qwen_home_radv_root=$qwen_home_opt/radv
    qwen_home_image_source=$qwen_home_opt/stable-diffusion.cpp
    qwen_home_image_runtime=$qwen_home_image_source/build-raven2/bin/sd-cli
    qwen_home_ryzenadj_source=$qwen_home_opt/ryzenadj/src
    qwen_home_ryzenadj=$qwen_home_bin/ryzenadj
    qwen_home_shaderc_root=$qwen_home_opt/shaderc
    qwen_home_searxng_root=$qwen_home_opt/searxng
    qwen_home_searxng_source=$qwen_home_searxng_root/src
    qwen_home_searxng_python=$qwen_home_searxng_root/venv/bin/python
    qwen_home_yacy=$qwen_home_opt/yacy
    qwen_home_rocm=$qwen_home_opt/rocm
    qwen_home_web_token_key=$qwen_home_state/web-token.key
    qwen_home_image_parameters=$qwen_home_state/image-parameters.json
    return 0
}

# The marker binds a root to the checkout that laid it out, so a root moved
# beside a second checkout is a root that second checkout refuses. The state
# is `unmarked` where no marker exists, which is a root `make bootstrap` has
# yet to lay out and every reader admits, `bound` where the marker's
# tree_root resolves to this tree, and `foreign:TREE` where it resolves
# elsewhere. Both sides are resolved through `cd -P` so a symlinked checkout
# compares equal to the path it points at.
qwen_home_binding_state() {
    if [ ! -f "$qwen_home_marker" ]; then
        printf 'unmarked\n'
        return 0
    fi
    qwen_home_marker_tree=$(sed -n 's/^tree_root=//p' "$qwen_home_marker")
    if [ -z "$qwen_home_marker_tree" ]; then
        printf 'foreign:unnamed\n'
        return 0
    fi
    if [ -d "$qwen_home_marker_tree" ]; then
        qwen_home_marker_tree=$(CDPATH='' cd -- "$qwen_home_marker_tree" && pwd -P)
    fi
    if [ "$qwen_home_marker_tree" = "$qwen_tree_root" ]; then
        printf 'bound\n'
    else
        printf 'foreign:%s\n' "$qwen_home_marker_tree"
    fi
}

# The refusal every reader of the root shares. A launcher, the manifest, and
# the removal actions all call it, so a root whose marker names another
# checkout stops the read rather than serving one checkout's declaration out
# of another checkout's tree.
qwen_home_require_binding() {
    qwen_home_binding=$(qwen_home_binding_state)
    case $qwen_home_binding in
        bound | unmarked) return 0 ;;
    esac
    printf '%s is bound to %s and this tree is %s; run make bootstrap in the checkout the marker names, or point QWEN_HOME at this tree'"'"'s own root\n' \
        "$qwen_home" "${qwen_home_binding#foreign:}" "$qwen_tree_root" >&2
    return 2
}

# A sourced library sees the caller's $0, so the caller's script_directory
# locates this file; the command form locates itself.
if [ "${script_directory:-}" != '' ] && [ -f "${script_directory}/qwen-home.sh" ]; then
    qwen_home_resolve "$script_directory" || exit 2
else
    qwen_home_command_directory=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)
    qwen_home_resolve "$qwen_home_command_directory" || exit 2
    case ${1:-} in
        print)
            shift
            [ "$#" -ge 1 ] || { printf 'usage: %s print NAME [NAME...]\n' "$0" >&2; exit 2; }
            for qwen_home_name in "$@"; do
                case " $qwen_home_names " in
                    *" $qwen_home_name "*) ;;
                    *)
                        printf 'unknown runtime root name: %s\n' "$qwen_home_name" >&2
                        exit 2
                        ;;
                esac
                eval "printf '%s\\n' \"\$$qwen_home_name\""
            done
            ;;
        paths)
            [ "$#" -eq 1 ] || { printf 'usage: %s paths\n' "$0" >&2; exit 2; }
            for qwen_home_name in $qwen_home_names; do
                eval "printf '%s\\t%s\\n' \"\$qwen_home_name\" \"\$$qwen_home_name\""
            done
            ;;
        *)
            printf 'usage: %s print NAME [NAME...] | paths\n' "$0" >&2
            exit 2
            ;;
    esac
fi
