"""The runtime root, resolved the way remote/qwen-home.sh resolves it.

QWEN_HOME names the one directory every generated byte lives under and
defaults to `.runtime` beside the `remote/` directory this module sits in, so
a python child reads the same root as the shell script that started it
without the value having to cross an environment boundary.
"""

from __future__ import annotations

import os
from pathlib import Path

RUNTIME_SCHEMA_VERSION = 1

_DECLARED = {
    "bin": "bin",
    "opt": "opt",
    "models": "models",
    "deployments": "deployments",
    "state": "state",
    "cache": "cache",
    "tmp": "tmp",
    "results": "results",
    "llama_source": "opt/llama.cpp",
    "image_source": "opt/stable-diffusion.cpp",
    "image_runtime": "opt/stable-diffusion.cpp/build-raven2/bin/sd-cli",
    "gguf_py": "opt/llama.cpp/gguf-py",
    "ryzenadj": "bin/ryzenadj",
    "searxng_root": "opt/searxng",
    "searxng_source": "opt/searxng/src",
    "searxng_python": "opt/searxng/venv/bin/python",
    "web_token_key": "state/web-token.key",
    "manifest": "manifest.tsv",
    "marker": ".qwen-runtime-root",
}


def tree_root() -> Path:
    """The tree that holds remote/, which is the tree whose root is read."""
    return Path(__file__).resolve().parent.parent


def home() -> Path:
    value = os.environ.get("QWEN_HOME")
    if value:
        root = Path(value)
        if not root.is_absolute():
            raise ValueError(f"QWEN_HOME must be an absolute path: {value}")
        return root
    return tree_root() / ".runtime"


def path(name: str) -> Path:
    try:
        relative = _DECLARED[name]
    except KeyError as error:
        raise KeyError(f"unknown runtime root name: {name}") from error
    return home() / relative
