#!/bin/sh
set -eu

# The runtime root as a declared, enumerable, removable object.
#
# remote/qwen-home.sh names the one directory every generated byte lives
# under; this script makes that declaration checkable. `init` lays out the
# root and writes its identity marker. `status` enumerates every component
# the repository claims ownership of, present or absent, into
# $QWEN_HOME/manifest.tsv with one row per component carrying its kind, path,
# source, revision, source digest, installed digest, mutability, and the
# command that rebuilds it. `doctor` reads the inverse: the paths a
# predecessor layout left outside the root, anything foreign under the root,
# and the transient system state a campaign writes and restores, classified
# as declared, legacy-known, foreign, or transient-system-state and touched
# by nothing. `uninstall` and `purge` remove the root only where the marker
# proves the directory is one this script laid out and
# `check-deletion-plan.sh` proves every object their selection holds
# disposable, and `purge-legacy` removes the enumerated predecessor paths and
# nothing else, under an explicit opt-in.
#
# The confirm each removal takes proves an operator meant to run the command.
# The preflight answers the separate question of what the command selected: a
# measurement acquisition or a deployment bundle that is unreviewed, held,
# changed since its review, locked by a producer, or unmanaged refuses the
# whole plan before the first sibling goes.
#
# The three verifications answer three different questions and fail for three
# different reasons, so they are three actions rather than one. `verify-layout`
# reads the structure alone: the marker, its schema, its binding, the layout
# directories, and any entry under the root outside the layout. It touches no
# installed component, so it answers on a root `make bootstrap` just laid out.
# `verify-components` reads the identity of every installed component out of
# the manifest and names each one present or absent, which is the question a
# receipt asks. `verify-live` reads the transient system state and the legacy
# summary, which move under a running campaign and belong to no build; it
# passes where a node is absent, since the workstation carries no amdgpu
# sysfs. `make verify` is their union beside the sudo policy and the ratchet.
#
# usage: runtime-root.sh paths|init|status|doctor|uninstall|purge|purge-legacy
#        runtime-root.sh verify-layout|verify-components|verify-live
#   QWEN_HOME                    the root, default .runtime beside remote/
#   QWEN_PURGE_LEGACY_CONFIRM    must read `yes` for purge-legacy
#   QWEN_RUNTIME_ROOT_CONFIRM    must equal QWEN_HOME for purge, and for
#                                uninstall of a root bound to a production checkout
#   QWEN_RUNTIME_ROOT_REBIND     must equal this tree for init over a foreign marker
#   QWEN_DOCTOR_HOME             doctor reads this in place of $HOME (fixtures)
#   QWEN_DOCTOR_SYSTEM_PREFIX    doctor prefixes absolute legacy paths (fixtures)
#   QWEN_DOCTOR_ACCOUNT_LOOKUP   command that tests a legacy account (fixtures)
#   QWEN_DELETION_JOURNAL        absolute path the removal records itself to,
#                                required for purge and refused inside the root

usage() {
    sed -n '33,44p' "$0" >&2
    exit 2
}

script_directory=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
# shellcheck source=remote/qwen-home.sh
. "$script_directory/qwen-home.sh"

[ "$#" -eq 1 ] || usage
action=$1

runtime_schema_version=1
layout_directories='bin opt models deployments state cache tmp results'

sha256_of() {
    sha256sum -- "$1" | cut -d ' ' -f 1
}

file_or_absent() {
    if [ -f "$1" ]; then sha256_of "$1"; else printf 'absent\n'; fi
}

git_head_or_absent() {
    if [ -d "$1/.git" ]; then
        git -C "$1" rev-parse HEAD 2>/dev/null || printf 'unreadable\n'
    else
        printf 'absent\n'
    fi
}

# A directory's identity is the digest of its sorted listing of relative
# path and byte count, which a 74 GB model tree yields in seconds where a
# content digest would take an hour; a model's own bytes are proven by the
# download script that pins them.
listing_digest_or_absent() {
    if [ -d "$1" ]; then
        (cd "$1" && find . -type f -printf '%P\t%s\n' | LC_ALL=C sort | sha256sum | cut -d ' ' -f 1)
    else
        printf 'absent\n'
    fi
}

tsv_row() {
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$@"
}

write_marker() {
    printf 'runtime_schema_version=%s\ntree_root=%s\n' \
        "$runtime_schema_version" "$qwen_tree_root" >"$qwen_home_marker"
}

require_marker() {
    qwen_home_require_binding || exit 2
    if [ ! -f "$qwen_home_marker" ]; then
        printf '%s carries no runtime-root marker (%s); this script removes only a root it laid out\n' \
            "$qwen_home" "$qwen_home_marker" >&2
        exit 2
    fi
    marker_version=$(sed -n 's/^runtime_schema_version=//p' "$qwen_home_marker")
    if [ "$marker_version" != "$runtime_schema_version" ]; then
        printf 'runtime-root marker states schema %s where this script reads %s\n' \
            "$marker_version" "$runtime_schema_version" >&2
        exit 2
    fi
}

status_rows() {
    tsv_row component kind path source revision source_sha256 installed_sha256 mutable rebuild_command
    tsv_row runtime-root marker "$qwen_home_marker" "$qwen_tree_root" "schema-$runtime_schema_version" - \
        "$(file_or_absent "$qwen_home_marker")" no 'make bootstrap'

    searxng_pins=$qwen_tree_root/toolchains/searxng/source.tsv
    searxng_lock=$qwen_tree_root/toolchains/searxng/requirements.lock
    searxng_pinned=$(awk -F'\t' '$1 == "pinned_commit" { print $2 }' "$searxng_pins" 2>/dev/null || printf '-')
    tsv_row searxng-source source "$qwen_home_searxng_source" github:searxng/searxng "${searxng_pinned:--}" \
        "$(file_or_absent "$searxng_pins")" "$(git_head_or_absent "$qwen_home_searxng_source")" no 'make install-searxng'
    searxng_venv_identity=absent
    if [ -x "$qwen_home_searxng_python" ]; then
        searxng_venv_identity=$("$qwen_home_searxng_python" -m pip freeze --disable-pip-version-check 2>/dev/null | LC_ALL=C sort | sha256sum | cut -d ' ' -f 1)
    fi
    tsv_row searxng-venv venv "$qwen_home_searxng_root/venv" toolchains/searxng/requirements.lock - \
        "$(file_or_absent "$searxng_lock")" "$searxng_venv_identity" no 'make install-searxng'

    wheelhouse_manifest_path=$qwen_home_searxng_root/wheelhouse/wheelhouse.tsv
    tsv_row searxng-wheelhouse wheels "$qwen_home_searxng_root/wheelhouse" \
        toolchains/searxng/requirements.lock - "$(file_or_absent "$searxng_lock")" \
        "$(file_or_absent "$wheelhouse_manifest_path")" no 'make searxng-wheelhouse'

    tsv_row ryzenadj binary "$qwen_home_ryzenadj" github:FlyGoat/RyzenAdj \
        "$(git_head_or_absent "$qwen_home_ryzenadj_source")" - "$(file_or_absent "$qwen_home_ryzenadj")" no 'make install-ryzenadj'
    tsv_row image-runtime binary "$qwen_home_image_runtime" github:leejet/stable-diffusion.cpp \
        "$(git_head_or_absent "$qwen_home_image_source")" - "$(file_or_absent "$qwen_home_image_runtime")" no 'make install-image-runtime'
    tsv_row llama-source source "$qwen_home_llama_source" github:ggml-org/llama.cpp \
        "$(git_head_or_absent "$qwen_home_llama_source")" "$(file_or_absent "$qwen_tree_root/remote/llama-patch-series.tsv")" - no 'make build-llama'
    tsv_row llama-server binary "$qwen_home_llama_server" remote/build-llama-preset.sh - - \
        "$(file_or_absent "$qwen_home_llama_server")" no 'make build-llama'
    shaderc_glslc=absent
    for candidate in "$qwen_home_shaderc_root"/*/bin/glslc; do
        [ -x "$candidate" ] && shaderc_glslc=$(sha256_of "$candidate")
    done
    tsv_row shaderc toolchain "$qwen_home_shaderc_root" remote/fetch-shaderc-toolchain.sh - - "$shaderc_glslc" no 'make install-shaderc'
    # The image parameter file is the geometry and the ceilings the service
    # runs a job under, so it is a component the root owns rather than a path
    # a caller names: qwen-image-launch.sh validates it against the ledger row
    # and image-launch-lib.sh refuses one resolving outside the root. It is
    # written per launch from the ledger, so its digest states which parameter
    # set the running service enforces.
    tsv_row image-parameters parameters "$qwen_home_image_parameters" remote/image-profiles.tsv - \
        "$(file_or_absent "$qwen_tree_root/remote/image-profiles.tsv")" \
        "$(file_or_absent "$qwen_home_image_parameters")" yes 'remote/qwen-image-launch.sh'
    tsv_row models artifacts "$qwen_home_models" remote/model-artifacts.tsv - \
        "$(file_or_absent "$qwen_tree_root/remote/model-artifacts.tsv")" "$(listing_digest_or_absent "$qwen_home_models")" no 'make install-models'
    deployment_current=absent
    if [ -L "$qwen_home_deployments/deployment-current" ]; then
        deployment_current=$(readlink "$qwen_home_deployments/deployment-current")
    fi
    tsv_row deployments bundles "$qwen_home_deployments" remote/build-deployment-bundle.sh "$deployment_current" - \
        "$(listing_digest_or_absent "$qwen_home_deployments")" no 'remote/build-deployment-bundle.sh'
    tsv_row state state "$qwen_home_state" - - - - yes -
    tsv_row cache cache "$qwen_home_cache" - - - - yes -
    tsv_row tmp scratch "$qwen_home_tmp" - - - - yes -
    tsv_row results results "$qwen_home_results" - - - - yes -

    sudo_policy_source=$qwen_tree_root/runtime/sudoers/90-qwen-agent
    sudo_policy_installed=unreadable
    if [ -r /etc/sudoers.d/90-qwen-agent ]; then
        sudo_policy_installed=$(sha256_of /etc/sudoers.d/90-qwen-agent)
    elif [ ! -e /etc/sudoers.d/90-qwen-agent ] && [ -d /etc/sudoers.d ] && [ -r /etc/sudoers.d ]; then
        sudo_policy_installed=absent
    elif sudo -n true 2>/dev/null; then
        sudo_policy_installed=$(sudo -n sha256sum /etc/sudoers.d/90-qwen-agent 2>/dev/null | cut -d ' ' -f 1 || printf 'absent')
        [ -n "$sudo_policy_installed" ] || sudo_policy_installed=absent
    fi
    tsv_row sudo-policy system-file /etc/sudoers.d/90-qwen-agent runtime/sudoers/90-qwen-agent - \
        "$(file_or_absent "$sudo_policy_source")" "$sudo_policy_installed" no 'make install-sudo-policy'
}

# Every predecessor path a launch or a build once wrote outside the root,
# named one by one so purge-legacy removes exactly these and doctor reports
# exactly these. `user` rows belong to the serving user and need no
# privilege; `system` rows were written by remote/install-searxng.sh in its
# service-account form and need sudo to remove; `account` names the service
# account that form created.
legacy_rows() {
    # The legacy table is a report rather than a requirement, so an unset HOME
    # leaves the user rows unenumerated and the system rows and the transient
    # state still answer. `make verify-live` runs in environments that carry
    # no HOME, and a refusal there would report an environment rather than the
    # appliance.
    legacy_home=${QWEN_DOCTOR_HOME:-${HOME:-}}
    if [ -z "$legacy_home" ]; then
        legacy_home=/nonexistent-home  # appliance-path: named
    fi
    legacy_prefix=${QWEN_DOCTOR_SYSTEM_PREFIX:-}
    for relative in qwen-laptop-setup qwen-deployments qwen-webui-state models \
        src/llama.cpp-qwen-apu src/llama.cpp-qwen-apu-trace src/llama.cpp \
        src/llama.cpp-alias src/llama.cpp-census src/llama.cpp-census-e4 \
        src/llama.cpp-census-v2 src/llama.cpp-census-v3 src/llama.cpp-census-v5 \
        src/llama.cpp-census-v6 src/llama.cpp-census-v7 src/llama.cpp-e4 \
        src/llama.cpp-lease src/llama.cpp-natural-boundary src/llama.cpp-q4k-scale \
        src/stable-diffusion.cpp-qwen-apu src/RyzenAdj src/ryzen_smu src/umr \
        src/qwen-apu-gates opt/yacy .local/bin/ryzenadj qwen-web-token.key \
        .cache/qwen-apu-build .cache/qwen-apu-gate .qwen-gate-venv \
        qwen-served-decode qwen-bandwidth-ladder qwen-depth-chain qwen-model-comparison; do
        printf 'user\t%s\n' "$legacy_home/$relative"
    done
    for absolute in /usr/local/searxng /etc/searxng /opt/searxng-qwen-apu /opt/yacy; do  # appliance-path: named
        printf 'system\t%s\n' "$legacy_prefix$absolute"
    done
    printf 'account\tsearxng\n'
}

account_exists() {
    if [ -n "${QWEN_DOCTOR_ACCOUNT_LOOKUP:-}" ]; then
        sh -c "$QWEN_DOCTOR_ACCOUNT_LOOKUP" lookup "$1" >/dev/null 2>&1
    else
        id "$1" >/dev/null 2>&1
    fi
}

doctor_report() {
    printf 'class\tpath\tdetail\n'
    printf 'declared\t%s\t%s\n' "$qwen_home" "runtime root"
    printf 'declared\t%s\tmarker binding %s, this tree %s\n' \
        "$qwen_home_marker" "$(qwen_home_binding_state)" "$qwen_tree_root"
    for relative in $layout_directories; do
        state=absent
        [ -d "$qwen_home/$relative" ] && state=present
        printf 'declared\t%s\t%s\n' "$qwen_home/$relative" "$state"
    done
    printf 'declared\t%s\t%s\n' "${QWEN_DOCTOR_SYSTEM_PREFIX:-}/etc/sudoers.d/90-qwen-agent" "sudo policy, source runtime/sudoers/90-qwen-agent"
    legacy_list=$(mktemp "${TMPDIR:-/tmp}/legacy-rows.XXXXXX")
    legacy_rows >"$legacy_list"
    while IFS="$(printf '\t')" read -r legacy_kind legacy_path; do
        case $legacy_kind in
            account)
                if account_exists "$legacy_path"; then
                    printf 'legacy-known\taccount:%s\tservice account, retired with purge-legacy\n' "$legacy_path"
                fi
                ;;
            *)
                if [ -e "$legacy_path" ] || [ -L "$legacy_path" ]; then
                    printf 'legacy-known\t%s\t%s path, retired with purge-legacy\n' "$legacy_path" "$legacy_kind"
                fi
                ;;
        esac
    done <"$legacy_list"
    rm -f "$legacy_list"
    if [ -d "$qwen_home" ]; then
        for entry in "$qwen_home"/* "$qwen_home"/.[!.]*; do
            [ -e "$entry" ] || [ -L "$entry" ] || continue
            entry_name=${entry##*/}
            case " $layout_directories manifest.tsv .qwen-runtime-root .deletion.lock .gitkeep " in
                *" $entry_name "*) ;;
                *) printf 'foreign\t%s\tunder the root and outside the layout\n' "$entry" ;;
            esac
        done
    fi
    # SQLite in WAL mode keeps a -wal journal and a -shm index beside each
    # cache, owned by the same account, so the three names are one cache.
    for cache_file in "${QWEN_DOCTOR_SYSTEM_PREFIX:-}"/tmp/sxng_cache_*.db \
        "${QWEN_DOCTOR_SYSTEM_PREFIX:-}"/tmp/sxng_cache_*.db-wal \
        "${QWEN_DOCTOR_SYSTEM_PREFIX:-}"/tmp/sxng_cache_*.db-shm; do
        [ -e "$cache_file" ] || continue
        printf 'legacy-known\t%s\tengine cache of the retired service-account instance\n' "$cache_file"
    done
    for node in /sys/class/drm/card0/device/power_dpm_force_performance_level \
        /sys/devices/system/cpu/cpufreq/boost /sys/kernel/mm/ksm/run; do
        [ -e "$node" ] || continue
        printf 'transient-system-state\t%s\t%s\n' "$node" "$(cat "$node" 2>/dev/null || printf 'unreadable')"
    done
}

verify_layout() {
    verify_failures=0
    if [ ! -d "$qwen_home" ]; then
        printf 'runtime root absent: %s (run make bootstrap)\n' "$qwen_home" >&2
        return 1
    fi
    printf 'layout_root=%s\n' "$qwen_home"
    if [ -f "$qwen_home_marker" ]; then
        marker_schema=$(sed -n 's/^runtime_schema_version=//p' "$qwen_home_marker")
        printf 'layout_marker=present schema=%s binding=%s\n' \
            "${marker_schema:--}" "$(qwen_home_binding_state)"
        if [ "$marker_schema" != "$runtime_schema_version" ]; then
            printf 'marker states schema %s where this script reads %s\n' \
                "${marker_schema:--}" "$runtime_schema_version" >&2
            verify_failures=$((verify_failures + 1))
        fi
    else
        printf 'layout_marker=absent\n'
        printf '%s carries no runtime-root marker; run make bootstrap\n' "$qwen_home" >&2
        verify_failures=$((verify_failures + 1))
    fi
    qwen_home_require_binding || verify_failures=$((verify_failures + 1))
    for relative in $layout_directories; do
        if [ -d "$qwen_home/$relative" ]; then
            printf 'layout_directory=%s state=present\n' "$relative"
        else
            printf 'layout_directory=%s state=absent\n' "$relative"
            verify_failures=$((verify_failures + 1))
        fi
    done
    layout_foreign=0
    for entry in "$qwen_home"/* "$qwen_home"/.[!.]*; do
        [ -e "$entry" ] || [ -L "$entry" ] || continue
        entry_name=${entry##*/}
        case " $layout_directories manifest.tsv .qwen-runtime-root .deletion.lock .gitkeep " in
            *" $entry_name "*) ;;
            *)
                printf 'layout_foreign=%s\n' "$entry"
                layout_foreign=$((layout_foreign + 1))
                ;;
        esac
    done
    printf 'verify_layout=%s foreign_entries=%s\n' \
        "$([ "$verify_failures" -eq 0 ] && [ "$layout_foreign" -eq 0 ] && printf 'passed' || printf 'failed')" \
        "$layout_foreign"
    [ "$verify_failures" -eq 0 ] && [ "$layout_foreign" -eq 0 ]
}

verify_components() {
    if [ ! -f "$qwen_home_manifest" ]; then
        printf 'no manifest at %s; run make status\n' "$qwen_home_manifest" >&2
        return 1
    fi
    # The manifest is the identity record and this reads it rather than
    # recomputing it, so `make status` is what a stale reading names as the
    # remedy. A mutable component declares no identity and is reported as
    # such; every other component is present or absent by its installed
    # digest.
    component_absent=0
    while IFS="$(printf '\t')" read -r component kind path source revision \
        source_digest installed_digest mutable rebuild; do
        [ "$component" = component ] && continue
        [ -n "$component" ] || continue
        case $mutable in
            yes) printf 'component=%s state=mutable path=%s\n' "$component" "$path"; continue ;;
        esac
        case $installed_digest in
            absent | unreadable | '' | -)
                printf 'component=%s state=absent rebuild=%s\n' "$component" "$rebuild"
                component_absent=$((component_absent + 1))
                ;;
            *)
                printf 'component=%s state=present installed_sha256=%s source=%s revision=%s source_sha256=%s kind=%s\n' \
                    "$component" "$installed_digest" "$source" "$revision" "$source_digest" "$kind"
                ;;
        esac
    done <"$qwen_home_manifest"
    printf 'verify_components=passed absent_components=%s manifest_sha256=%s\n' \
        "$component_absent" "$(sha256_of "$qwen_home_manifest")"
}

# The transient half: the sysfs a campaign writes and restores, and the
# legacy summary the doctor computes. A node absent from this machine is
# reported as absent and passes, since the workstation carries no amdgpu
# sysfs and a verification that refused there would refuse every gate run.
verify_live() {
    for node in /sys/class/drm/card0/device/power_dpm_force_performance_level \
        /sys/devices/system/cpu/cpufreq/boost /sys/kernel/mm/ksm/run; do
        if [ -e "$node" ]; then
            printf 'live_node=%s value=%s\n' "$node" "$(cat "$node" 2>/dev/null || printf 'unreadable')"
        else
            printf 'live_node=%s value=absent\n' "$node"
        fi
    done
    live_session=absent
    if [ -f "$qwen_home_state/session.status" ]; then
        live_session=$(sed -n 's/^state=\([A-Za-z-]*\).*/\1/p' "$qwen_home_state/session.status" | head -n 1)
        [ -n "$live_session" ] || live_session=unreadable
    fi
    live_doctor=$(doctor_report)
    live_legacy=$(printf '%s\n' "$live_doctor" | grep -c '^legacy-known' || true)
    live_foreign=$(printf '%s\n' "$live_doctor" | grep -c '^foreign' || true)
    printf 'verify_live=passed session_state=%s legacy_paths=%s foreign_owned_paths=%s\n' \
        "$live_session" "$live_legacy" "$live_foreign"
}

case $action in
    paths)
        "$script_directory/qwen-home.sh" paths
        ;;
    init)
        # A marker naming another checkout is the case the binding exists to
        # catch, and `make bootstrap` is the first remedy a refused reader
        # reaches for, so init rewrites such a marker only where
        # QWEN_RUNTIME_ROOT_REBIND names this tree. Without that rule the
        # remedy silently steals the root the refusal reported.
        init_binding=$(qwen_home_binding_state)
        case $init_binding in
            bound | unmarked) ;;
            *)
                if [ "${QWEN_RUNTIME_ROOT_REBIND:-}" != "$qwen_tree_root" ]; then
                    printf '%s is bound to %s; rebinding it to %s discards that checkout'"'"'s claim, so set QWEN_RUNTIME_ROOT_REBIND to that exact tree\n' \
                        "$qwen_home" "${init_binding#foreign:}" "$qwen_tree_root" >&2
                    exit 2
                fi
                printf 'rebound %s from %s\n' "$qwen_home" "${init_binding#foreign:}"
                ;;
        esac
        mkdir -p "$qwen_home"
        for relative in $layout_directories; do
            mkdir -p "$qwen_home/$relative"
        done
        write_marker
        printf 'runtime_root=%s schema=%s\n' "$qwen_home" "$runtime_schema_version"
        ;;
    status)
        qwen_home_require_binding || exit 2
        if [ ! -d "$qwen_home" ]; then
            printf 'runtime root absent: %s (run make bootstrap)\n' "$qwen_home" >&2
            exit 1
        fi
        manifest_staging=$(mktemp "$qwen_home/.manifest.XXXXXX")
        status_rows >"$manifest_staging"
        mv -f "$manifest_staging" "$qwen_home_manifest"
        cat "$qwen_home_manifest"
        printf 'runtime_manifest=%s runtime_manifest_sha256=%s\n' \
            "$qwen_home_manifest" "$(sha256_of "$qwen_home_manifest")"
        ;;
    verify-layout)
        verify_layout
        ;;
    verify-components)
        qwen_home_require_binding || exit 2
        verify_components
        ;;
    verify-live)
        verify_live
        ;;
    doctor)
        doctor_output=$(doctor_report)
        printf '%s\n' "$doctor_output"
        legacy_count=$(printf '%s\n' "$doctor_output" | grep -c '^legacy-known' || true)
        foreign_count=$(printf '%s\n' "$doctor_output" | grep -c '^foreign' || true)
        legacy_present=no
        [ "$legacy_count" -eq 0 ] || legacy_present=yes
        printf 'legacy_paths_present=%s legacy_paths=%s foreign_owned_paths=%s\n' \
            "$legacy_present" "$legacy_count" "$foreign_count"
        ;;
    uninstall | purge)
        require_marker
        if [ -f "$qwen_home_state/session.status" ] && \
            grep -q '^state=running' "$qwen_home_state/session.status" 2>/dev/null; then
            printf 'the appliance is running under %s; run remote/qwen-teardown.sh first\n' \
                "$qwen_home_state" >&2
            exit 2
        fi
        if [ "$action" = purge ] && [ "${QWEN_RUNTIME_ROOT_CONFIRM:-}" != "$qwen_home" ]; then
            printf 'purge removes %s whole, models and state included; set QWEN_RUNTIME_ROOT_CONFIRM to that exact path\n' \
                "$qwen_home" >&2
            exit 2
        fi
        # A production checkout is the one git tree with its own object
        # store: a linked worktree carries .git as a gitdir file and a
        # fixture tree carries none, so the discriminator names the tree
        # the appliance serves from without naming any path. The root the
        # marker bound to such a tree holds the served deployments and the
        # session state, so uninstall takes the confirm purge already takes
        # rather than removing 74 GB of reproducible products on a bare
        # command.
        if [ "$action" = uninstall ] && [ -d "$qwen_tree_root/.git" ] && \
            [ "${QWEN_RUNTIME_ROOT_CONFIRM:-}" != "$qwen_home" ]; then
            printf 'the marker binds %s to the production checkout %s; set QWEN_RUNTIME_ROOT_CONFIRM to that exact root to uninstall it\n' \
                "$qwen_home" "$qwen_tree_root" >&2
            exit 2
        fi
        # The journal records what the removal did, so it lives where the
        # removal cannot reach it. `state` survives uninstall and carries the
        # default; purge removes `state` too, so it requires a path an
        # operator names outside the root rather than writing the record of an
        # operation into the bytes that operation destroys.
        deletion_journal=${QWEN_DELETION_JOURNAL:-}
        if [ "$action" = purge ] && [ -z "$deletion_journal" ]; then
            printf 'purge removes %s whole, the state directory included; set QWEN_DELETION_JOURNAL to a path outside that root\n' \
                "$qwen_home" >&2
            exit 2
        fi
        [ -n "$deletion_journal" ] || deletion_journal=$qwen_home_state/deletion-journal.tsv
        case $deletion_journal in
            /*) ;;
            *)
                printf 'QWEN_DELETION_JOURNAL must be an absolute path: %s\n' "$deletion_journal" >&2
                exit 2
                ;;
        esac
        if [ "$action" = purge ]; then
            journal_directory=$(CDPATH='' cd -- "$(dirname -- "$deletion_journal")" 2>/dev/null && pwd -P) || journal_directory=
            if [ -z "$journal_directory" ]; then
                printf 'the journal directory does not resolve: %s\n' "$deletion_journal" >&2
                exit 2
            fi
            case $journal_directory in
                "$qwen_home" | "$qwen_home"/*)
                    printf 'the journal %s resolves inside %s, which purge removes; name a path outside that root\n' \
                        "$deletion_journal" "$qwen_home" >&2
                    exit 2
                    ;;
            esac
        fi

        # One exclusion covers the classification and the removal together. A
        # plan verified by a process that then exits leaves the interval
        # between the check and the act open to a producer that starts inside
        # it, so the descriptor is opened before the plan runs and held until
        # the last entry is gone. The helper refuses a symlink, a directory, a
        # foreign owner, a multiply-linked leaf, and a group-writable mode,
        # and carries descriptor 7 across the one exec.
        deletion_lock_path=$qwen_home/.deletion.lock
        case ${QWEN_DELETION_LOCK_DESCRIPTOR_INHERITED:-0} in
            0)
                QWEN_DELETION_LOCK_DESCRIPTOR_INHERITED=1
                export QWEN_DELETION_LOCK_DESCRIPTOR_INHERITED
                exec "$script_directory/open-verified-lock-descriptor.py" open \
                    --normalize-legacy-mode "$deletion_lock_path" 7 "$0" "$action"
                ;;
            1)
                "$script_directory/open-verified-lock-descriptor.py" verify "$deletion_lock_path" 7
                ;;
            *)
                printf 'invalid deletion-lock inheritance marker: %s\n' \
                    "$QWEN_DELETION_LOCK_DESCRIPTOR_INHERITED" >&2
                exit 2
                ;;
        esac
        flock -x 7

        # The complete selection is classified before the first byte goes, so
        # a plan holding one object it cannot prove disposable refuses whole
        # and no sibling is removed while a protected object stands
        # unresolved.
        deletion_plan_report=$(mktemp "${TMPDIR:-/tmp}/deletion-preflight.XXXXXX")
        if ! "$script_directory/check-deletion-plan.sh" plan "$action" >"$deletion_plan_report" 2>&1; then
            cat "$deletion_plan_report" >&2
            rm -f "$deletion_plan_report"
            exit 1
        fi
        cat "$deletion_plan_report"
        deletion_plan_identity=$(sed -n 's/.*plan_sha256=\([0-9a-f]*\).*/\1/p' "$deletion_plan_report" | head -n 1)

        mkdir -p -- "$(dirname -- "$deletion_journal")"
        printf 'field\tvalue\naction\t%s\nroot\t%s\nplan_sha256\t%s\nbegan_at\t%s\n' \
            "$action" "$qwen_home" "$deletion_plan_identity" \
            "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" >"$deletion_journal"

        # The removal iterates the root-level rows of the plan it just read
        # rather than taking a second reading of the root, so an entry that
        # appeared after the classification is outside what this loop can
        # reach instead of being removed unclassified. A row whose path lies
        # directly under the root is one such entry; the expanded acquisition
        # and deployment rows below them are covered by their container.
        deletion_entries=$(mktemp "${TMPDIR:-/tmp}/deletion-entries.XXXXXX")
        awk -F'\t' -v root="$qwen_home/" '
            NR > 1 && index($4, root) == 1 {
                relative = substr($4, length(root) + 1)
                if (relative !~ /\//) { print $4 }
            }
        ' "$deletion_plan_report" | LC_ALL=C sort -u >"$deletion_entries"

        deletion_incomplete=0
        while IFS= read -r entry; do
            [ -n "$entry" ] || continue
            [ -e "$entry" ] || [ -L "$entry" ] || continue
            entry_name=${entry##*/}
            case $entry_name in
                state | models)
                    if [ "$action" != purge ]; then
                        printf 'kept %s\n' "$entry"
                        printf 'kept\t%s\n' "$entry" >>"$deletion_journal"
                        continue
                    fi
                    ;;
            esac
            rm -rf -- "$entry" 2>/dev/null || true
            if [ -e "$entry" ] || [ -L "$entry" ]; then
                # A sequence of removals is one sequence rather than one
                # transaction, and bytes already gone do not return. The
                # journal states where the run stopped and what still stands
                # rather than reporting a success the tree does not hold.
                printf 'residue\t%s\n' "$entry" >>"$deletion_journal"
                printf 'residue %s\n' "$entry" >&2
                deletion_incomplete=1
                break
            fi
            printf 'removed %s\n' "$entry"
            printf 'removed\t%s\n' "$entry" >>"$deletion_journal"
        done <"$deletion_entries"
        rm -f "$deletion_entries" "$deletion_plan_report"
        # The exclusion leaf stays out of the plan so its creation cannot move
        # the plan identity, so purge removes it here rather than leaving the
        # one entry behind in a root it emptied. The descriptor this shell
        # holds outlives the name.
        [ "$action" != purge ] || rm -f "$deletion_lock_path"
        deletion_state=complete
        [ "$deletion_incomplete" -eq 0 ] || deletion_state=incomplete
        printf 'ended_at\t%s\njournal\t%s\n' \
            "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$deletion_state" >>"$deletion_journal"
        printf 'deletion_journal=%s state=%s\n' "$deletion_journal" "$deletion_state"
        if [ "$deletion_incomplete" -ne 0 ]; then
            printf '%s stopped part way; %s names what was removed and what stands\n' \
                "$action" "$deletion_journal" >&2
            exit 1
        fi
        if [ "$action" = uninstall ]; then
            write_marker
        fi
        ;;
    purge-legacy)
        if [ "${QWEN_PURGE_LEGACY_CONFIRM:-}" != yes ]; then
            printf 'purge-legacy removes the enumerated predecessor paths outside %s; set QWEN_PURGE_LEGACY_CONFIRM=yes\n' \
                "$qwen_home" >&2
            legacy_rows | sed 's/^/  /' >&2
            exit 2
        fi
        # The replacement must stand before its predecessor goes: a purge of
        # the retired SearXNG install with no instance under the root would
        # leave the web lane with nothing to launch.
        if [ ! -x "$qwen_home_searxng_python" ]; then
            printf 'no SearXNG instance under %s; run make install-searxng and verify it before purging the legacy install\n' \
                "$qwen_home_searxng_root" >&2
            exit 2
        fi
        for cache_file in "${QWEN_DOCTOR_SYSTEM_PREFIX:-}"/tmp/sxng_cache_*.db \
            "${QWEN_DOCTOR_SYSTEM_PREFIX:-}"/tmp/sxng_cache_*.db-wal \
            "${QWEN_DOCTOR_SYSTEM_PREFIX:-}"/tmp/sxng_cache_*.db-shm; do
            [ -e "$cache_file" ] || continue
            if [ -n "${QWEN_DOCTOR_SYSTEM_PREFIX:-}" ] || [ "$(stat -c %U "$cache_file")" = "$(id -un)" ]; then
                rm -f -- "$cache_file"
            else
                sudo -n rm -f -- "$cache_file"
            fi
            printf 'removed %s\n' "$cache_file"
        done
        legacy_list=$(mktemp "${TMPDIR:-/tmp}/legacy-rows.XXXXXX")
        legacy_rows >"$legacy_list"
        purge_residue=0
        while IFS="$(printf '\t')" read -r legacy_kind legacy_path; do
            case $legacy_kind in
                user)
                    # A user path can hold entries a privileged build wrote
                    # inside it (a kernel-module tree's __pycache__ owned by
                    # root), which the unprivileged removal leaves behind.
                    # The same enumerated path is then removed under sudo -n
                    # on the appliance; the fixture prefix has no privilege
                    # to spend, so residue there is reported and the loop
                    # continues to the remaining rows, and the run ends
                    # non-zero once every row has been attempted.
                    if [ -e "$legacy_path" ] || [ -L "$legacy_path" ]; then
                        rm -rf -- "$legacy_path" 2>/dev/null || true
                        if { [ -e "$legacy_path" ] || [ -L "$legacy_path" ]; } \
                            && [ -z "${QWEN_DOCTOR_SYSTEM_PREFIX:-}" ]; then
                            sudo -n rm -rf -- "$legacy_path" 2>/dev/null || true
                        fi
                        if [ -e "$legacy_path" ] || [ -L "$legacy_path" ]; then
                            printf 'residue %s (entries the serving user cannot remove)\n' "$legacy_path"
                            purge_residue=$((purge_residue + 1))
                        else
                            printf 'removed %s\n' "$legacy_path"
                        fi
                    fi
                    ;;
                system)
                    if [ -e "$legacy_path" ] || [ -L "$legacy_path" ]; then
                        if [ -n "${QWEN_DOCTOR_SYSTEM_PREFIX:-}" ]; then
                            rm -rf -- "$legacy_path"
                        else
                            sudo -n rm -rf -- "$legacy_path"
                        fi
                        printf 'removed %s\n' "$legacy_path"
                    fi
                    ;;
                account)
                    if account_exists "$legacy_path" && [ -z "${QWEN_DOCTOR_SYSTEM_PREFIX:-}" ]; then
                        # The account goes only once nothing runs as it and no
                        # file outside the enumerated paths belongs to it.
                        if pgrep -u "$legacy_path" >/dev/null 2>&1; then
                            printf 'processes still run as %s; refusing to remove the account\n' "$legacy_path" >&2
                            rm -f "$legacy_list"
                            exit 1
                        fi
                        stray_files=$(sudo -n find / -xdev -user "$legacy_path" -print 2>/dev/null | head -n 20 || true)
                        if [ -n "$stray_files" ]; then
                            printf 'files owned by %s remain outside the enumerated paths:\n%s\n' "$legacy_path" "$stray_files" >&2
                            rm -f "$legacy_list"
                            exit 1
                        fi
                        sudo -n userdel "$legacy_path"
                        printf 'removed account %s\n' "$legacy_path"
                    fi
                    ;;
            esac
        done <"$legacy_list"
        rm -f "$legacy_list"
        if [ "$purge_residue" -ne 0 ]; then
            printf 'purge-legacy left %s enumerated path(s) with residue\n' "$purge_residue" >&2
            exit 1
        fi
        ;;
    *) usage ;;
esac
