#!/bin/sh
set -eu

# The runtime root as a declared, enumerable, removable object.
#
# remote/qwen-home.sh names the one directory every generated byte lives
# under; this script makes that declaration checkable. `init` lays out the
# root and writes its identity marker. `status` enumerates every component
# the repository claims ownership of, present or absent, into
# $QWEN_HOME/manifest.tsv with one row per component carrying its kind, path,
# source, revision, source digest, installed digest, mutability, and the
# command that rebuilds it. `doctor` reads the inverse: the paths a
# predecessor layout left outside the root, anything foreign under the root,
# and the transient system state a campaign writes and restores, classified
# as declared, legacy-known, foreign, or transient-system-state and touched
# by nothing. `uninstall` and `purge` remove the root only where the marker
# proves the directory is one this script laid out, and `purge-legacy`
# removes the enumerated predecessor paths and nothing else, under an
# explicit opt-in.
#
# usage: runtime-root.sh paths|init|status|doctor|uninstall|purge|purge-legacy
#   QWEN_HOME                    the root, default .runtime beside remote/
#   QWEN_PURGE_LEGACY_CONFIRM    must read `yes` for purge-legacy
#   QWEN_RUNTIME_ROOT_CONFIRM    must equal QWEN_HOME for purge
#   QWEN_DOCTOR_HOME             doctor reads this in place of $HOME (fixtures)
#   QWEN_DOCTOR_SYSTEM_PREFIX    doctor prefixes absolute legacy paths (fixtures)
#   QWEN_DOCTOR_ACCOUNT_LOOKUP   command that tests a legacy account (fixtures)

usage() {
    sed -n '21,28p' "$0" >&2
    exit 2
}

script_directory=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
# shellcheck source=remote/qwen-home.sh
. "$script_directory/qwen-home.sh"

[ "$#" -eq 1 ] || usage
action=$1

runtime_schema_version=1
layout_directories='bin opt models deployments state cache tmp results'

sha256_of() {
    sha256sum -- "$1" | cut -d ' ' -f 1
}

file_or_absent() {
    if [ -f "$1" ]; then sha256_of "$1"; else printf 'absent\n'; fi
}

git_head_or_absent() {
    if [ -d "$1/.git" ]; then
        git -C "$1" rev-parse HEAD 2>/dev/null || printf 'unreadable\n'
    else
        printf 'absent\n'
    fi
}

# A directory's identity is the digest of its sorted listing of relative
# path and byte count, which a 74 GB model tree yields in seconds where a
# content digest would take an hour; a model's own bytes are proven by the
# download script that pins them.
listing_digest_or_absent() {
    if [ -d "$1" ]; then
        (cd "$1" && find . -type f -printf '%P\t%s\n' | LC_ALL=C sort | sha256sum | cut -d ' ' -f 1)
    else
        printf 'absent\n'
    fi
}

tsv_row() {
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$@"
}

write_marker() {
    printf 'runtime_schema_version=%s\ntree_root=%s\n' \
        "$runtime_schema_version" "$qwen_tree_root" >"$qwen_home_marker"
}

require_marker() {
    qwen_home_require_binding || exit 2
    if [ ! -f "$qwen_home_marker" ]; then
        printf '%s carries no runtime-root marker (%s); this script removes only a root it laid out\n' \
            "$qwen_home" "$qwen_home_marker" >&2
        exit 2
    fi
    marker_version=$(sed -n 's/^runtime_schema_version=//p' "$qwen_home_marker")
    if [ "$marker_version" != "$runtime_schema_version" ]; then
        printf 'runtime-root marker states schema %s where this script reads %s\n' \
            "$marker_version" "$runtime_schema_version" >&2
        exit 2
    fi
}

status_rows() {
    tsv_row component kind path source revision source_sha256 installed_sha256 mutable rebuild_command
    tsv_row runtime-root marker "$qwen_home_marker" "$qwen_tree_root" "schema-$runtime_schema_version" - \
        "$(file_or_absent "$qwen_home_marker")" no 'make bootstrap'

    searxng_pins=$qwen_tree_root/toolchains/searxng/source.tsv
    searxng_lock=$qwen_tree_root/toolchains/searxng/requirements.lock
    searxng_pinned=$(awk -F'\t' '$1 == "pinned_commit" { print $2 }' "$searxng_pins" 2>/dev/null || printf '-')
    tsv_row searxng-source source "$qwen_home_searxng_source" github:searxng/searxng "${searxng_pinned:--}" \
        "$(file_or_absent "$searxng_pins")" "$(git_head_or_absent "$qwen_home_searxng_source")" no 'make install-searxng'
    searxng_venv_identity=absent
    if [ -x "$qwen_home_searxng_python" ]; then
        searxng_venv_identity=$("$qwen_home_searxng_python" -m pip freeze --disable-pip-version-check 2>/dev/null | LC_ALL=C sort | sha256sum | cut -d ' ' -f 1)
    fi
    tsv_row searxng-venv venv "$qwen_home_searxng_root/venv" toolchains/searxng/requirements.lock - \
        "$(file_or_absent "$searxng_lock")" "$searxng_venv_identity" no 'make install-searxng'

    tsv_row ryzenadj binary "$qwen_home_ryzenadj" github:FlyGoat/RyzenAdj \
        "$(git_head_or_absent "$qwen_home_ryzenadj_source")" - "$(file_or_absent "$qwen_home_ryzenadj")" no 'make install-ryzenadj'
    tsv_row image-runtime binary "$qwen_home_image_runtime" github:leejet/stable-diffusion.cpp \
        "$(git_head_or_absent "$qwen_home_image_source")" - "$(file_or_absent "$qwen_home_image_runtime")" no 'make install-image-runtime'
    tsv_row llama-source source "$qwen_home_llama_source" github:ggml-org/llama.cpp \
        "$(git_head_or_absent "$qwen_home_llama_source")" "$(file_or_absent "$qwen_tree_root/remote/llama-patch-series.tsv")" - no 'make build-llama'
    tsv_row llama-server binary "$qwen_home_llama_server" remote/build-llama-preset.sh - - \
        "$(file_or_absent "$qwen_home_llama_server")" no 'make build-llama'
    shaderc_glslc=absent
    for candidate in "$qwen_home_shaderc_root"/*/bin/glslc; do
        [ -x "$candidate" ] && shaderc_glslc=$(sha256_of "$candidate")
    done
    tsv_row shaderc toolchain "$qwen_home_shaderc_root" remote/fetch-shaderc-toolchain.sh - - "$shaderc_glslc" no 'make install-shaderc'
    tsv_row models artifacts "$qwen_home_models" remote/model-artifacts.tsv - \
        "$(file_or_absent "$qwen_tree_root/remote/model-artifacts.tsv")" "$(listing_digest_or_absent "$qwen_home_models")" no 'make install-models'
    deployment_current=absent
    if [ -L "$qwen_home_deployments/deployment-current" ]; then
        deployment_current=$(readlink "$qwen_home_deployments/deployment-current")
    fi
    tsv_row deployments bundles "$qwen_home_deployments" remote/build-deployment-bundle.sh "$deployment_current" - \
        "$(listing_digest_or_absent "$qwen_home_deployments")" no 'remote/build-deployment-bundle.sh'
    tsv_row state state "$qwen_home_state" - - - - yes -
    tsv_row cache cache "$qwen_home_cache" - - - - yes -
    tsv_row tmp scratch "$qwen_home_tmp" - - - - yes -
    tsv_row results results "$qwen_home_results" - - - - yes -

    sudo_policy_source=$qwen_tree_root/runtime/sudoers/90-qwen-agent
    sudo_policy_installed=unreadable
    if [ -r /etc/sudoers.d/90-qwen-agent ]; then
        sudo_policy_installed=$(sha256_of /etc/sudoers.d/90-qwen-agent)
    elif [ ! -e /etc/sudoers.d/90-qwen-agent ] && [ -d /etc/sudoers.d ] && [ -r /etc/sudoers.d ]; then
        sudo_policy_installed=absent
    elif sudo -n true 2>/dev/null; then
        sudo_policy_installed=$(sudo -n sha256sum /etc/sudoers.d/90-qwen-agent 2>/dev/null | cut -d ' ' -f 1 || printf 'absent')
        [ -n "$sudo_policy_installed" ] || sudo_policy_installed=absent
    fi
    tsv_row sudo-policy system-file /etc/sudoers.d/90-qwen-agent runtime/sudoers/90-qwen-agent - \
        "$(file_or_absent "$sudo_policy_source")" "$sudo_policy_installed" no 'make install-sudo-policy'
}

# Every predecessor path a launch or a build once wrote outside the root,
# named one by one so purge-legacy removes exactly these and doctor reports
# exactly these. `user` rows belong to the serving user and need no
# privilege; `system` rows were written by remote/install-searxng.sh in its
# service-account form and need sudo to remove; `account` names the service
# account that form created.
legacy_rows() {
    legacy_home=${QWEN_DOCTOR_HOME:-${HOME:?}}
    legacy_prefix=${QWEN_DOCTOR_SYSTEM_PREFIX:-}
    for relative in qwen-laptop-setup qwen-deployments qwen-webui-state models \
        src/llama.cpp-qwen-apu src/llama.cpp-qwen-apu-trace src/llama.cpp \
        src/llama.cpp-alias src/llama.cpp-census src/llama.cpp-census-e4 \
        src/llama.cpp-census-v2 src/llama.cpp-census-v3 src/llama.cpp-census-v5 \
        src/llama.cpp-census-v6 src/llama.cpp-census-v7 src/llama.cpp-e4 \
        src/llama.cpp-lease src/llama.cpp-natural-boundary src/llama.cpp-q4k-scale \
        src/stable-diffusion.cpp-qwen-apu src/RyzenAdj src/ryzen_smu src/umr \
        src/qwen-apu-gates opt/yacy .local/bin/ryzenadj qwen-web-token.key \
        .cache/qwen-apu-build .cache/qwen-apu-gate .qwen-gate-venv \
        qwen-served-decode qwen-bandwidth-ladder qwen-depth-chain qwen-model-comparison; do
        printf 'user\t%s\n' "$legacy_home/$relative"
    done
    for absolute in /usr/local/searxng /etc/searxng /opt/searxng-qwen-apu /opt/yacy; do  # appliance-path: named
        printf 'system\t%s\n' "$legacy_prefix$absolute"
    done
    printf 'account\tsearxng\n'
}

account_exists() {
    if [ -n "${QWEN_DOCTOR_ACCOUNT_LOOKUP:-}" ]; then
        sh -c "$QWEN_DOCTOR_ACCOUNT_LOOKUP" lookup "$1" >/dev/null 2>&1
    else
        id "$1" >/dev/null 2>&1
    fi
}

doctor_report() {
    printf 'class\tpath\tdetail\n'
    printf 'declared\t%s\t%s\n' "$qwen_home" "runtime root"
    printf 'declared\t%s\tmarker binding %s, this tree %s\n' \
        "$qwen_home_marker" "$(qwen_home_binding_state)" "$qwen_tree_root"
    for relative in $layout_directories; do
        state=absent
        [ -d "$qwen_home/$relative" ] && state=present
        printf 'declared\t%s\t%s\n' "$qwen_home/$relative" "$state"
    done
    printf 'declared\t%s\t%s\n' "${QWEN_DOCTOR_SYSTEM_PREFIX:-}/etc/sudoers.d/90-qwen-agent" "sudo policy, source runtime/sudoers/90-qwen-agent"
    legacy_list=$(mktemp "${TMPDIR:-/tmp}/legacy-rows.XXXXXX")
    legacy_rows >"$legacy_list"
    while IFS="$(printf '\t')" read -r legacy_kind legacy_path; do
        case $legacy_kind in
            account)
                if account_exists "$legacy_path"; then
                    printf 'legacy-known\taccount:%s\tservice account, retired with purge-legacy\n' "$legacy_path"
                fi
                ;;
            *)
                if [ -e "$legacy_path" ] || [ -L "$legacy_path" ]; then
                    printf 'legacy-known\t%s\t%s path, retired with purge-legacy\n' "$legacy_path" "$legacy_kind"
                fi
                ;;
        esac
    done <"$legacy_list"
    rm -f "$legacy_list"
    if [ -d "$qwen_home" ]; then
        for entry in "$qwen_home"/* "$qwen_home"/.[!.]*; do
            [ -e "$entry" ] || [ -L "$entry" ] || continue
            entry_name=${entry##*/}
            case " $layout_directories manifest.tsv .qwen-runtime-root .gitkeep " in
                *" $entry_name "*) ;;
                *) printf 'foreign\t%s\tunder the root and outside the layout\n' "$entry" ;;
            esac
        done
    fi
    # SQLite in WAL mode keeps a -wal journal and a -shm index beside each
    # cache, owned by the same account, so the three names are one cache.
    for cache_file in "${QWEN_DOCTOR_SYSTEM_PREFIX:-}"/tmp/sxng_cache_*.db \
        "${QWEN_DOCTOR_SYSTEM_PREFIX:-}"/tmp/sxng_cache_*.db-wal \
        "${QWEN_DOCTOR_SYSTEM_PREFIX:-}"/tmp/sxng_cache_*.db-shm; do
        [ -e "$cache_file" ] || continue
        printf 'legacy-known\t%s\tengine cache of the retired service-account instance\n' "$cache_file"
    done
    for node in /sys/class/drm/card0/device/power_dpm_force_performance_level \
        /sys/devices/system/cpu/cpufreq/boost /sys/kernel/mm/ksm/run; do
        [ -e "$node" ] || continue
        printf 'transient-system-state\t%s\t%s\n' "$node" "$(cat "$node" 2>/dev/null || printf 'unreadable')"
    done
}

case $action in
    paths)
        "$script_directory/qwen-home.sh" paths
        ;;
    init)
        # A marker naming another checkout is the case the binding exists to
        # catch, and `make bootstrap` is the first remedy a refused reader
        # reaches for, so init rewrites such a marker only where
        # QWEN_RUNTIME_ROOT_REBIND names this tree. Without that rule the
        # remedy silently steals the root the refusal reported.
        init_binding=$(qwen_home_binding_state)
        case $init_binding in
            bound | unmarked) ;;
            *)
                if [ "${QWEN_RUNTIME_ROOT_REBIND:-}" != "$qwen_tree_root" ]; then
                    printf '%s is bound to %s; rebinding it to %s discards that checkout'"'"'s claim, so set QWEN_RUNTIME_ROOT_REBIND to that exact tree\n' \
                        "$qwen_home" "${init_binding#foreign:}" "$qwen_tree_root" >&2
                    exit 2
                fi
                printf 'rebound %s from %s\n' "$qwen_home" "${init_binding#foreign:}"
                ;;
        esac
        mkdir -p "$qwen_home"
        for relative in $layout_directories; do
            mkdir -p "$qwen_home/$relative"
        done
        write_marker
        printf 'runtime_root=%s schema=%s\n' "$qwen_home" "$runtime_schema_version"
        ;;
    status)
        qwen_home_require_binding || exit 2
        if [ ! -d "$qwen_home" ]; then
            printf 'runtime root absent: %s (run make bootstrap)\n' "$qwen_home" >&2
            exit 1
        fi
        manifest_staging=$(mktemp "$qwen_home/.manifest.XXXXXX")
        status_rows >"$manifest_staging"
        mv -f "$manifest_staging" "$qwen_home_manifest"
        cat "$qwen_home_manifest"
        printf 'runtime_manifest=%s runtime_manifest_sha256=%s\n' \
            "$qwen_home_manifest" "$(sha256_of "$qwen_home_manifest")"
        ;;
    doctor)
        doctor_output=$(doctor_report)
        printf '%s\n' "$doctor_output"
        legacy_count=$(printf '%s\n' "$doctor_output" | grep -c '^legacy-known' || true)
        foreign_count=$(printf '%s\n' "$doctor_output" | grep -c '^foreign' || true)
        legacy_present=no
        [ "$legacy_count" -eq 0 ] || legacy_present=yes
        printf 'legacy_paths_present=%s legacy_paths=%s foreign_owned_paths=%s\n' \
            "$legacy_present" "$legacy_count" "$foreign_count"
        ;;
    uninstall | purge)
        require_marker
        if [ -f "$qwen_home_state/session.status" ] && \
            grep -q '^state=running' "$qwen_home_state/session.status" 2>/dev/null; then
            printf 'the appliance is running under %s; run remote/qwen-teardown.sh first\n' \
                "$qwen_home_state" >&2
            exit 2
        fi
        if [ "$action" = purge ] && [ "${QWEN_RUNTIME_ROOT_CONFIRM:-}" != "$qwen_home" ]; then
            printf 'purge removes %s whole, models and state included; set QWEN_RUNTIME_ROOT_CONFIRM to that exact path\n' \
                "$qwen_home" >&2
            exit 2
        fi
        for entry in "$qwen_home"/* "$qwen_home"/.[!.]*; do
            [ -e "$entry" ] || [ -L "$entry" ] || continue
            entry_name=${entry##*/}
            case $entry_name in
                .gitkeep) continue ;;
                state | models)
                    [ "$action" = purge ] || { printf 'kept %s\n' "$entry"; continue; }
                    ;;
            esac
            rm -rf -- "$entry"
            printf 'removed %s\n' "$entry"
        done
        if [ "$action" = uninstall ]; then
            write_marker
        fi
        ;;
    purge-legacy)
        if [ "${QWEN_PURGE_LEGACY_CONFIRM:-}" != yes ]; then
            printf 'purge-legacy removes the enumerated predecessor paths outside %s; set QWEN_PURGE_LEGACY_CONFIRM=yes\n' \
                "$qwen_home" >&2
            legacy_rows | sed 's/^/  /' >&2
            exit 2
        fi
        # The replacement must stand before its predecessor goes: a purge of
        # the retired SearXNG install with no instance under the root would
        # leave the web lane with nothing to launch.
        if [ ! -x "$qwen_home_searxng_python" ]; then
            printf 'no SearXNG instance under %s; run make install-searxng and verify it before purging the legacy install\n' \
                "$qwen_home_searxng_root" >&2
            exit 2
        fi
        for cache_file in "${QWEN_DOCTOR_SYSTEM_PREFIX:-}"/tmp/sxng_cache_*.db \
            "${QWEN_DOCTOR_SYSTEM_PREFIX:-}"/tmp/sxng_cache_*.db-wal \
            "${QWEN_DOCTOR_SYSTEM_PREFIX:-}"/tmp/sxng_cache_*.db-shm; do
            [ -e "$cache_file" ] || continue
            if [ -n "${QWEN_DOCTOR_SYSTEM_PREFIX:-}" ] || [ "$(stat -c %U "$cache_file")" = "$(id -un)" ]; then
                rm -f -- "$cache_file"
            else
                sudo -n rm -f -- "$cache_file"
            fi
            printf 'removed %s\n' "$cache_file"
        done
        legacy_list=$(mktemp "${TMPDIR:-/tmp}/legacy-rows.XXXXXX")
        legacy_rows >"$legacy_list"
        purge_residue=0
        while IFS="$(printf '\t')" read -r legacy_kind legacy_path; do
            case $legacy_kind in
                user)
                    # A user path can hold entries a privileged build wrote
                    # inside it (a kernel-module tree's __pycache__ owned by
                    # root), which the unprivileged removal leaves behind.
                    # The same enumerated path is then removed under sudo -n
                    # on the appliance; the fixture prefix has no privilege
                    # to spend, so residue there is reported and the loop
                    # continues to the remaining rows, and the run ends
                    # non-zero once every row has been attempted.
                    if [ -e "$legacy_path" ] || [ -L "$legacy_path" ]; then
                        rm -rf -- "$legacy_path" 2>/dev/null || true
                        if { [ -e "$legacy_path" ] || [ -L "$legacy_path" ]; } \
                            && [ -z "${QWEN_DOCTOR_SYSTEM_PREFIX:-}" ]; then
                            sudo -n rm -rf -- "$legacy_path" 2>/dev/null || true
                        fi
                        if [ -e "$legacy_path" ] || [ -L "$legacy_path" ]; then
                            printf 'residue %s (entries the serving user cannot remove)\n' "$legacy_path"
                            purge_residue=$((purge_residue + 1))
                        else
                            printf 'removed %s\n' "$legacy_path"
                        fi
                    fi
                    ;;
                system)
                    if [ -e "$legacy_path" ] || [ -L "$legacy_path" ]; then
                        if [ -n "${QWEN_DOCTOR_SYSTEM_PREFIX:-}" ]; then
                            rm -rf -- "$legacy_path"
                        else
                            sudo -n rm -rf -- "$legacy_path"
                        fi
                        printf 'removed %s\n' "$legacy_path"
                    fi
                    ;;
                account)
                    if account_exists "$legacy_path" && [ -z "${QWEN_DOCTOR_SYSTEM_PREFIX:-}" ]; then
                        # The account goes only once nothing runs as it and no
                        # file outside the enumerated paths belongs to it.
                        if pgrep -u "$legacy_path" >/dev/null 2>&1; then
                            printf 'processes still run as %s; refusing to remove the account\n' "$legacy_path" >&2
                            rm -f "$legacy_list"
                            exit 1
                        fi
                        stray_files=$(sudo -n find / -xdev -user "$legacy_path" -print 2>/dev/null | head -n 20 || true)
                        if [ -n "$stray_files" ]; then
                            printf 'files owned by %s remain outside the enumerated paths:\n%s\n' "$legacy_path" "$stray_files" >&2
                            rm -f "$legacy_list"
                            exit 1
                        fi
                        sudo -n userdel "$legacy_path"
                        printf 'removed account %s\n' "$legacy_path"
                    fi
                    ;;
            esac
        done <"$legacy_list"
        rm -f "$legacy_list"
        if [ "$purge_residue" -ne 0 ]; then
            printf 'purge-legacy left %s enumerated path(s) with residue\n' "$purge_residue" >&2
            exit 1
        fi
        ;;
    *) usage ;;
esac
