#!/bin/sh
set -eu

# The image generation UI half of PR D reaches the network through the same
# one-human-approval discipline the web search tool uses, with its own grant
# context and its own synchronous state machine. Grep asserts the structural
# properties against the served file the way
# test-fallback-webui-web-authorization.sh does for the web tools, so the
# gate runs wherever the tree is cloned; the node blocks below exercise the
# pure functions when node is on the path.

if [ "$#" -ne 0 ]; then
    printf 'usage: %s\n' "$0" >&2
    exit 2
fi

script_directory=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
fallback_ui=$script_directory/../webui/index.html

# The per-turn Image toggle governs the tool list rather than the request
# text, so a turn run with it off carries no generate_image call to propose,
# and a proposal carried over from a turn that offered it reaches no
# generation once the toggle reads off for the current turn.
grep -F '<input type="checkbox" id="image-tools">' "$fallback_ui" >/dev/null
grep -F "const imagePermission = \$('#image-tools').checked;" "$fallback_ui" >/dev/null
if [ "$(grep -c "\$('#image-tools').checked = false;" "$fallback_ui")" -lt 2 ]; then
    printf 'fallback Web UI does not reset the Image toggle at both init and the turn boundary\n' >&2
    exit 1
fi
grep -F 'if (imagePermission) {' "$fallback_ui" >/dev/null
grep -F "const { definition } = await resolveImageTools(requestModel, modelStateGeneration);" \
    "$fallback_ui" >/dev/null
grep -F "const IMAGE_TOOL_NAME = 'generate_image';" "$fallback_ui" >/dev/null
grep -F "if (!imagePermission) {" "$fallback_ui" >/dev/null
grep -F 'The image surface is off for this turn; ${toolName} did not run.' "$fallback_ui" >/dev/null

# The listing is a second, independent read of GET /tools: it reuses
# fetchWebToolListing and webToolDefinition rather than duplicating either,
# and keeps its own cache so a rename of the web tool names does not move it.
grep -F 'async function resolveImageTools(selectedModel, generation) {' "$fallback_ui" >/dev/null
grep -F 'listed = await fetchWebToolListing(selectedModel);' "$fallback_ui" >/dev/null
grep -F "const entry = listed.find(row => row && row.tool === IMAGE_TOOL_NAME);" \
    "$fallback_ui" >/dev/null
grep -F 'const definition = entry ? webToolDefinition(entry) : null;' "$fallback_ui" >/dev/null
grep -F 'function forgetImageTools() {' "$fallback_ui" >/dev/null
if [ "$(grep -c 'forgetImageTools();' "$fallback_ui")" -lt 2 ]; then
    printf 'fallback Web UI does not clear the image tool cache on every model reselection\n' >&2
    exit 1
fi
grep -F 'function findImageCancelToolName(listing) {' "$fallback_ui" >/dev/null

# The dialog names every field the grant is signed over, including the seed
# this page generates when the model omits one.
grep -F "row('prompt'" "$fallback_ui" >/dev/null
grep -F "row('negative prompt'" "$fallback_ui" >/dev/null
grep -F "row('seed'" "$fallback_ui" >/dev/null
grep -F "row('width'" "$fallback_ui" >/dev/null
grep -F "row('height'" "$fallback_ui" >/dev/null
grep -F "row('steps'" "$fallback_ui" >/dev/null
grep -F "row('profile'" "$fallback_ui" >/dev/null
grep -F 'id="image-approve-once"' "$fallback_ui" >/dev/null
grep -F 'id="image-approve-deny"' "$fallback_ui" >/dev/null
grep -F 'generated by this page; the model proposed no seed' "$fallback_ui" >/dev/null

# Randomness is never chosen after authorization: the seed is generated with
# the browser's cryptographic RNG before the dialog opens, not inside the
# approval handler.
grep -F 'function randomSeed() {' "$fallback_ui" >/dev/null
grep -F 'crypto.getRandomValues(new Uint32Array(1))[0];' "$fallback_ui" >/dev/null
seed_line=$(grep -n 'seed = randomSeed();' "$fallback_ui" | cut -d: -f1)
dialog_line=$(grep -n 'function approveImageGeneration' "$fallback_ui" | cut -d: -f1)
if [ -z "$seed_line" ] || [ -z "$dialog_line" ] || [ "$seed_line" -ge "$dialog_line" ]; then
    printf 'fallback Web UI does not generate the seed ahead of the approval dialog\n' >&2
    exit 1
fi

# The grant is signed over hashes of the prompts rather than the prompts
# themselves, and over an aspect and a max-dimension bound rather than the
# raw pixel size, and it names the qwen-image-generate-v1 context and the
# conversation generation.
grep -F "const IMAGE_GRANT_CONTEXT = 'qwen-image-generate-v1';" "$fallback_ui" >/dev/null
grep -F 'async function sha256Hex(text) {' "$fallback_ui" >/dev/null
grep -F 'function aspectRatio(width, height) {' "$fallback_ui" >/dev/null
grep -F 'async function imageGrantFields(fields, languageProfile, conversationGenerationValue) {' \
    "$fallback_ui" >/dev/null
grep -F 'context: IMAGE_GRANT_CONTEXT,' "$fallback_ui" >/dev/null
grep -F 'language_profile: languageProfile,' "$fallback_ui" >/dev/null
grep -F 'image_profile: fields.profile,' "$fallback_ui" >/dev/null
grep -F 'prompt_hash: promptHash,' "$fallback_ui" >/dev/null
grep -F 'negative_prompt_hash: negativePromptHash,' "$fallback_ui" >/dev/null
grep -F 'aspect: aspectRatio(fields.width, fields.height),' "$fallback_ui" >/dev/null
grep -F 'max_dimension: Math.max(fields.width, fields.height),' "$fallback_ui" >/dev/null
grep -F 'max_steps: fields.steps,' "$fallback_ui" >/dev/null
grep -F 'conversation_generation: conversationGenerationValue' "$fallback_ui" >/dev/null
grep -F "fetch(\`\${brokerOrigin()}/grant-image\`, {" "$fallback_ui" >/dev/null

# The grant reaches exactly one call site -- the params object of the one
# POST /tools body the approved generation runs under -- and the transcript
# never carries it.
grep -F 'function imageRequestParams(fields, authorization) {' "$fallback_ui" >/dev/null
# remote/image-mcp/server.py names the argument profile_id, requires it, and
# refuses any name outside its schema, so the request carries that spelling.
grep -F 'profile_id: fields.profile,' "$fallback_ui" >/dev/null
if [ "$(grep -c 'imageOutcome.authorization' "$fallback_ui")" -ne 1 ]; then
    printf 'fallback Web UI reads the issued image grant at more than one site\n' >&2
    exit 1
fi
if grep -E 'answerCall\([^)]*imageOutcome\.authorization' "$fallback_ui" >/dev/null; then
    printf 'fallback Web UI writes an image grant into the transcript\n' >&2
    exit 1
fi

# The synchronous state line reads Approved -> Generating image... -> Image
# complete, or Image failed with the reason read from body.error the way the
# refused, cancelled, and failed MCP statuses all arrive.
grep -F "renderImageState(stateEl, 'Approved');" "$fallback_ui" >/dev/null
grep -F "renderImageState(stateEl, 'Generating image...');" "$fallback_ui" >/dev/null
grep -F "renderImageState(stateEl, 'Image complete');" "$fallback_ui" >/dev/null
grep -F 'renderImageState(stateEl, `Image failed: ${payload.error}`, true);' "$fallback_ui" >/dev/null
grep -F "function parseCompletedImageResult(text) {" "$fallback_ui" >/dev/null
grep -F "if (parsed.status !== 'completed') {" "$fallback_ui" >/dev/null
grep -F 'typeof parsed.sha256' "$fallback_ui" >/dev/null
grep -F 'typeof parsed.provenance_url' "$fallback_ui" >/dev/null

# The client-side wait is the browser's own bound alone and names no
# runtime, image-service, MCP, or router deadline.
grep -F 'const IMAGE_GENERATION_TIMEOUT_MS = 660000;' "$fallback_ui" >/dev/null
grep -F 'setTimeout(() => controller.abort(), IMAGE_GENERATION_TIMEOUT_MS);' "$fallback_ui" >/dev/null

# A Cancel button aborts the fetch and, only when the served tool set names a
# cancel tool, also posts a best-effort cancel; either way the abort itself
# always runs.
grep -F 'async function postCancelBestEffort(cancelToolName, model) {' "$fallback_ui" >/dev/null
grep -F 'if (!cancelToolName) return;' "$fallback_ui" >/dev/null
grep -F 'cancelled = true;' "$fallback_ui" >/dev/null
grep -F 'void postCancelBestEffort(cancelToolName, model);' "$fallback_ui" >/dev/null

# The artifact card fetches the PNG with the page's own credential header
# into a blob URL, because <img src> cannot carry that header, and revokes
# the blob URL when the card is removed. The route is derived from the digest
# rather than taken from the result: image-service.py's provenance_url names
# the `.json` record and its artifact_url names the `.png`, both from the same
# digest, so a page that fetched the provenance route would read the record
# where it wanted the image.
grep -F 'async function loadArtifactBlobUrl(sha256) {' "$fallback_ui" >/dev/null
grep -F '`${artifactOrigin()}/artifacts/${sha256}.png`' "$fallback_ui" >/dev/null
grep -F 'loadArtifactBlobUrl(result.sha256)' "$fallback_ui" >/dev/null
grep -F "mode: 'cors', headers: authHeaders() });" "$fallback_ui" >/dev/null

# image-service.py binds its artifact listener on an ephemeral port and the
# router proxies none of its routes, so the origin is configured rather than
# resolved against the page, and a page given none says so instead of asking
# the router for a route it does not serve.
grep -F 'function configuredArtifactOrigin() {' "$fallback_ui" >/dev/null
grep -F "searchParams.get('artifacts')" "$fallback_ui" >/dev/null
grep -F 'meta[name="qwen-image-artifacts"]' "$fallback_ui" >/dev/null
grep -F "throw new Error('no artifact listener origin is configured for this page');" \
    "$fallback_ui" >/dev/null
grep -F 'return URL.createObjectURL(blob);' "$fallback_ui" >/dev/null
grep -F 'if (blobUrl) URL.revokeObjectURL(blobUrl);' "$fallback_ui" >/dev/null
grep -F 'function renderImageArtifactCard(container, fields, result) {' "$fallback_ui" >/dev/null
grep -F "\`sha256 \${result.sha256}\`," "$fallback_ui" >/dev/null
grep -F "\`seed \${fields.seed}\`," "$fallback_ui" >/dev/null
grep -F "\`\${fields.width}x\${fields.height}\`," "$fallback_ui" >/dev/null
grep -F "\`\${fields.steps} steps\`," "$fallback_ui" >/dev/null

# The hash never substitutes for the credential header as an authorization
# query parameter.
if grep -E "loadArtifactBlobUrl\([^)]*\)" "$fallback_ui" | grep -qi 'sha256='; then
    printf 'fallback Web UI carries the artifact hash as a query-string credential\n' >&2
    exit 1
fi

# The retained transcript message names the sha256 and the provenance URL
# alone, never the image bytes and never the grant.
grep -F 'function buildImageToolResultSummary(result) {' "$fallback_ui" >/dev/null
grep -F 'Image generated: sha256 ${result.sha256}, provenance ${result.provenanceUrl}.' \
    "$fallback_ui" >/dev/null

# One image generation is authorized per turn, mirroring the one-search
# budget the web tool enforces.
grep -F 'const IMAGE_GENERATE_BUDGET_PER_TURN = 1;' "$fallback_ui" >/dev/null
grep -F 'const imageBudget = { remaining: IMAGE_GENERATE_BUDGET_PER_TURN };' "$fallback_ui" >/dev/null
grep -F 'if (imageBudget.remaining <= 0) {' "$fallback_ui" >/dev/null
grep -F 'imageBudget.remaining--;' "$fallback_ui" >/dev/null

# A field missing or malformed in the proposal fails the dialog closed rather
# than substituting a value nobody proposed or authored.
grep -F 'function proposedImageFields(argumentText) {' "$fallback_ui" >/dev/null
grep -F "must be a non-empty string" "$fallback_ui" >/dev/null
grep -F 'const requirePositiveInteger = key => {' "$fallback_ui" >/dev/null

# node exercises the pure parsing and hashing functions directly, when node
# is on the path.
if command -v node >/dev/null 2>&1; then
    node -e '
const fs = require("fs");
const crypto = require("crypto");
const source = fs.readFileSync(process.argv[1], "utf8");

function extract(startMarker, endMarker) {
    const start = source.indexOf(startMarker);
    if (start < 0) throw new Error("marker not found: " + startMarker);
    const end = source.indexOf(endMarker, start);
    if (end < 0) throw new Error("end marker not found: " + endMarker);
    return source.slice(start, end);
}

const globalCrypto = {
    getRandomValues: arr => { for (let i = 0; i < arr.length; i++) arr[i] = 42 + i; return arr; },
    subtle: {
        digest: async (_algorithm, bytes) => {
            const hash = crypto.createHash("sha256");
            hash.update(Buffer.from(bytes));
            return hash.digest().buffer;
        }
    }
};
globalThis.crypto = globalCrypto;

eval(extract(
    "const IMAGE_GRANT_CONTEXT = ",
    "// ==== end image generation: proposal parsing and grant"
));
// A second, separate span: the execution/rendering block is a disjoint run
// of function definitions further down the file, so it needs its own
// extract() rather than widening the first span across the intervening
// top-level code (boot(), the toggle resets, the broker-origin wiring) that
// executes immediately on eval and has no DOM in this node sandbox.
eval(extract(
    "function imageRequestParams(fields, authorization) {",
    "// ==== end image generation: execution and rendering"
));

// proposedImageFields: a well-formed proposal with no seed generates one and
// marks it generated; the same proposal with a seed keeps it as proposed.
const noSeed = proposedImageFields(JSON.stringify({
    prompt: "a fox in a field", profile: "sdxs-512", width: 512, height: 512, steps: 4
}));
if (!noSeed.seedGenerated) throw new Error("an omitted seed was not marked generated");
if (!Number.isInteger(noSeed.seed)) throw new Error("a generated seed is not an integer");

const withSeed = proposedImageFields(JSON.stringify({
    prompt: "a fox", profile: "sdxs-512", width: 512, height: 512, steps: 4, seed: 7
}));
if (withSeed.seedGenerated) throw new Error("a proposed seed was overwritten as generated");
if (withSeed.seed !== 7) throw new Error("a proposed seed was not carried through");

for (const malformed of [
    {}, { prompt: "" }, { prompt: "x", profile: "p" },
    { prompt: "x", profile: "p", width: 0, height: 512, steps: 4 },
    { prompt: "x", profile: "p", width: 512, height: 512, steps: 4, seed: -1 },
    { prompt: "x", profile: "p", width: 512, height: 512, steps: 4, seed: 1.5 },
]) {
    let threw = false;
    try { proposedImageFields(JSON.stringify(malformed)); } catch { threw = true; }
    if (!threw) throw new Error("a malformed proposal was not refused: " + JSON.stringify(malformed));
}

// aspectRatio reduces by the GCD.
if (aspectRatio(1024, 512) !== "2:1") throw new Error("aspectRatio did not reduce 1024x512");
if (aspectRatio(512, 512) !== "1:1") throw new Error("aspectRatio did not reduce a square");

// parseCompletedImageResult reads sha256 and provenance_url from a completed
// status and refuses every other shape, including the three terminal
// non-completed statuses (which the served path answers through
// payload.error instead and never routes through this function).
const completed = parseCompletedImageResult(JSON.stringify({
    status: "completed", sha256: "a".repeat(64), provenance_url: "/artifacts/aaa.png"
}));
if (completed.sha256 !== "a".repeat(64)) throw new Error("sha256 was not read from a completed result");
if (completed.provenanceUrl !== "/artifacts/aaa.png") {
    throw new Error("provenance_url was not read from a completed result");
}
for (const badStatus of ["accepted", "refused", "cancelled", "failed"]) {
    let threw = false;
    try {
        parseCompletedImageResult(JSON.stringify({
            status: badStatus, sha256: "a".repeat(64), provenance_url: "/artifacts/aaa.png"
        }));
    } catch { threw = true; }
    if (!threw) throw new Error("a non-completed status reached parseCompletedImageResult unrefused: " + badStatus);
}

// buildImageToolResultSummary names sha256 and the provenance URL and
// nothing else -- checked structurally since the function itself is the
// single call site that builds the retained transcript message.
const summary = buildImageToolResultSummary({ sha256: "b".repeat(64), provenanceUrl: "/artifacts/bbb.png" });
if (!summary.includes("b".repeat(64)) || !summary.includes("/artifacts/bbb.png")) {
    throw new Error("buildImageToolResultSummary dropped the sha256 or the provenance URL");
}

// imageGrantFields hashes each prompt rather than carrying it in the clear.
imageGrantFields(
    { prompt: "a fox", negative_prompt: "blurry", profile: "sdxs-512", seed: 7, width: 512, height: 512, steps: 4 },
    "lang-profile", 3
).then(grant => {
    if (grant.context !== "qwen-image-generate-v1") throw new Error("grant carries the wrong context");
    if (grant.prompt_hash === "a fox" || grant.prompt_hash.length !== 64) {
        throw new Error("grant does not carry a SHA-256 hex digest for the prompt");
    }
    if (grant.negative_prompt_hash.length !== 64) {
        throw new Error("grant does not carry a SHA-256 hex digest for the negative prompt");
    }
    if (grant.aspect !== "1:1") throw new Error("grant aspect was not derived from width and height");
    if (grant.max_dimension !== 512) throw new Error("grant max_dimension was not the larger side");
    if (grant.conversation_generation !== 3) throw new Error("grant did not carry the conversation generation");
}).catch(error => { console.error(error.message); process.exit(1); });
' "$fallback_ui"
fi

printf 'fallback_webui_image_authorization=accepted\n'
