"""The runtime root, the one directory every generated byte lives under.

QWEN_HOME names the root and defaults to `.runtime` beside `remote/` in the
tree that holds this package, so a checkout and its root resolve together
without the value crossing an environment boundary. This module carries the
same declared names, in the same order and with the same relative paths, as
`remote/qwen-home.sh`; `tests/test_runtime_paths.py` compares the two
authorities line for line, and a name added on one side without the other
fails that comparison. The marker binds a root to the checkout that laid it
out with two lines, `runtime_schema_version=` and `tree_root=`, and every
reader refuses a marker naming another tree.
"""

from __future__ import annotations

import os
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path

RUNTIME_SCHEMA_VERSION = 1
MARKER_NAME = ".qwen-runtime-root"

# The layout directories `init` creates and `verify-layout` admits. The shell
# authority lists the same set in `layout_directories`; venv, artifacts, and
# logs join the original eight for the Python control plane.
LAYOUT_DIRECTORIES: tuple[str, ...] = (
    "bin",
    "opt",
    "models",
    "deployments",
    "state",
    "cache",
    "tmp",
    "results",
    "venv",
    "artifacts",
    "logs",
)

# Declared names in shell order: (name, path relative to the root). The tree
# root and the root itself are computed rather than relative.
_DECLARED: tuple[tuple[str, str], ...] = (
    ("qwen_home_marker", MARKER_NAME),
    ("qwen_home_manifest", "manifest.tsv"),
    ("qwen_home_bin", "bin"),
    ("qwen_home_opt", "opt"),
    ("qwen_home_models", "models"),
    ("qwen_home_deployments", "deployments"),
    ("qwen_home_state", "state"),
    ("qwen_home_cache", "cache"),
    ("qwen_home_tmp", "tmp"),
    ("qwen_home_results", "results"),
    ("qwen_home_build_cache", "cache/build"),
    ("qwen_home_gate_cache", "cache/gate"),
    ("qwen_home_gate_venv", "opt/gate-venv"),
    ("qwen_home_browser_python", "opt/browser-venv/bin/python"),
    ("qwen_home_llama_source", "opt/llama.cpp"),
    ("qwen_home_llama_server", "opt/llama.cpp/build-appliance-current/bin/llama-server"),
    ("qwen_home_llama_bench", "opt/llama.cpp/build-qwen-vulkan/bin/llama-bench"),
    ("qwen_home_llama_cli", "opt/llama.cpp/build-qwen-vulkan/bin/llama-cli"),
    ("qwen_home_llama_quantize", "opt/llama.cpp/build-qwen-vulkan/bin/llama-quantize"),
    ("qwen_home_gguf_py", "opt/llama.cpp/gguf-py"),
    ("qwen_home_llama_upstream", "opt/llama.cpp-upstream"),
    ("qwen_home_llama_trace", "opt/llama.cpp-trace"),
    (
        "qwen_home_llama_census_bench",
        "opt/llama.cpp-census/build-raven2-vulkan-census/bin/llama-bench",
    ),
    ("qwen_home_radv_root", "opt/radv"),
    ("qwen_home_image_source", "opt/stable-diffusion.cpp"),
    ("qwen_home_image_runtime", "opt/stable-diffusion.cpp/build-raven2/bin/sd-cli"),
    ("qwen_home_ryzenadj_source", "opt/ryzenadj/src"),
    ("qwen_home_ryzenadj", "bin/ryzenadj"),
    ("qwen_home_shaderc_root", "opt/shaderc"),
    ("qwen_home_searxng_root", "opt/searxng"),
    ("qwen_home_searxng_source", "opt/searxng/src"),
    ("qwen_home_searxng_python", "opt/searxng/venv/bin/python"),
    ("qwen_home_yacy", "opt/yacy"),
    ("qwen_home_rocm", "opt/rocm"),
    ("qwen_home_web_token_key", "state/web-token.key"),
    ("qwen_home_image_parameters", "state/image-parameters.json"),
)

# Names the Python control plane adds beyond the shell set. They live in a
# separate table so the parity test compares the shared prefix exactly.
_PYTHON_ONLY: tuple[tuple[str, str], ...] = (
    ("qwen_home_venv", "venv"),
    ("qwen_home_venv_python", "venv/bin/python"),
    ("qwen_home_venv_cli", "venv/bin/qwen-apu"),
    ("qwen_home_artifacts", "artifacts"),
    ("qwen_home_logs", "logs"),
    ("qwen_home_control_socket", "state/control.sock"),
    ("qwen_home_supervisor_pid", "state/supervisor.pid"),
    ("qwen_home_runtime_state", "state/runtime.json"),
    ("qwen_home_workload_lock", "state/workload.lock"),
    ("qwen_home_database", "state/qwen-apu.sqlite3"),
    ("qwen_home_llama_store", "opt/llama"),
    ("qwen_home_image_store", "opt/stable-diffusion"),
)

SHELL_NAMES: tuple[str, ...] = ("qwen_tree_root", "qwen_home") + tuple(n for n, _ in _DECLARED)
ALL_NAMES: tuple[str, ...] = SHELL_NAMES + tuple(n for n, _ in _PYTHON_ONLY)


class RuntimeRootError(RuntimeError):
    """A root whose location or binding refuses this checkout."""


def tree_root(anchor: Path | None = None) -> Path:
    """The checkout that holds `remote/` and `src/`.

    The package sits at `src/qwen_apu/runtime/paths.py`, four levels below
    the tree; an installed copy (site-packages) has no `remote/` above it and
    reads QWEN_TREE_ROOT instead, which the venv's bootstrap records.
    """
    if anchor is not None:
        return anchor.resolve()
    declared = os.environ.get("QWEN_TREE_ROOT")
    if declared:
        return Path(declared).resolve()
    candidate = Path(__file__).resolve().parents[3]
    if (candidate / "remote").is_dir():
        return candidate
    raise RuntimeRootError(
        f"{candidate} holds no remote/ directory; set QWEN_TREE_ROOT to the checkout"
    )


def home(tree: Path | None = None) -> Path:
    value = os.environ.get("QWEN_HOME")
    if value:
        root = Path(value)
        if not root.is_absolute():
            raise RuntimeRootError(f"QWEN_HOME must be an absolute path: {value}")
        return root
    return (tree or tree_root()) / ".runtime"


@dataclass(frozen=True)
class RuntimePaths:
    """Every declared location, resolved once for one tree and one root."""

    tree: Path
    root: Path

    @classmethod
    def resolve(cls, tree: Path | None = None) -> RuntimePaths:
        resolved_tree = tree.resolve() if tree else tree_root()
        return cls(tree=resolved_tree, root=home(resolved_tree))

    def __getitem__(self, name: str) -> Path:
        if name == "qwen_tree_root":
            return self.tree
        if name == "qwen_home":
            return self.root
        for table in (_DECLARED, _PYTHON_ONLY):
            for declared, relative in table:
                if declared == name:
                    return self.root / relative
        raise KeyError(f"unknown runtime root name: {name}")

    def items(self, *, shell_only: bool = False) -> Iterator[tuple[str, Path]]:
        for name in SHELL_NAMES if shell_only else ALL_NAMES:
            yield name, self[name]

    @property
    def marker(self) -> Path:
        return self["qwen_home_marker"]

    def binding_state(self) -> str:
        """`unmarked`, `bound`, or `foreign:TREE`, as the shell reports it."""
        try:
            text = self.marker.read_text(encoding="utf-8")
        except OSError:
            return "unmarked"
        named = ""
        for line in text.splitlines():
            if line.startswith("tree_root="):
                named = line[len("tree_root=") :]
                break
        if not named:
            return "foreign:unnamed"
        resolved = Path(named)
        if resolved.is_dir():
            resolved = resolved.resolve()
        if resolved == self.tree:
            return "bound"
        return f"foreign:{resolved}"

    def marker_schema(self) -> int | None:
        try:
            text = self.marker.read_text(encoding="utf-8")
        except OSError:
            return None
        for line in text.splitlines():
            if line.startswith("runtime_schema_version="):
                value = line[len("runtime_schema_version=") :]
                return int(value) if value.isdigit() else None
        return None

    def require_binding(self) -> None:
        state = self.binding_state()
        if state in ("bound", "unmarked"):
            return
        raise RuntimeRootError(
            f"{self.root} is bound to {state[len('foreign:') :]} and this tree is "
            f"{self.tree}; run bootstrap in the checkout the marker names, or point "
            "QWEN_HOME at this tree's own root"
        )

    def write_marker(self) -> None:
        self.marker.write_text(
            f"runtime_schema_version={RUNTIME_SCHEMA_VERSION}\ntree_root={self.tree}\n",
            encoding="utf-8",
        )

    def lay_out(self, *, rebind: str | None = None) -> str:
        """Create the root and every layout directory and write the marker.

        A marker naming another checkout is rewritten only where `rebind`
        equals this tree exactly, the rule `runtime-root.sh init` applies to
        QWEN_RUNTIME_ROOT_REBIND. Returns `bound` or `rebound:TREE`.
        """
        state = self.binding_state()
        outcome = "bound"
        if state not in ("bound", "unmarked"):
            previous = state[len("foreign:") :]
            if rebind != str(self.tree):
                raise RuntimeRootError(
                    f"{self.root} is bound to {previous}; rebinding it to {self.tree} "
                    "discards that checkout's claim, so set QWEN_RUNTIME_ROOT_REBIND "
                    "to that exact tree"
                )
            outcome = f"rebound:{previous}"
        self.root.mkdir(parents=True, exist_ok=True)
        for relative in LAYOUT_DIRECTORIES:
            (self.root / relative).mkdir(parents=True, exist_ok=True)
        self.write_marker()
        return outcome

    def is_inside_root(self, target: Path) -> bool:
        """Whether a path (resolved) lies under the root, the write boundary."""
        try:
            target.resolve().relative_to(self.root.resolve())
        except ValueError:
            return False
        return True


def render_paths(paths: RuntimePaths, *, shell_only: bool = False) -> str:
    return "".join(f"{name}\t{value}\n" for name, value in paths.items(shell_only=shell_only))
